-- ============================================================
-- supabase/seed.sql
-- Hilfe-zur-Pflege — reproducible config seed
--
-- Run automatically by:  supabase db reset  /  supabase start
--
-- All config data (social_office, care_home, questionnaire,
-- category, question_group, question, question_option,
-- postal_code_rule) is owned by migrations as of the
-- 20260702000001_baseline_questionnaire_state migration.
--
-- This file previously duplicated that same data (from before
-- the questionnaire was edited directly in the Supabase dashboard).
-- Because `supabase db reset` applies this file AFTER all
-- migrations, the stale duplicate silently reverted every fix
-- the baseline migration made on every reset. Left as a no-op
-- to keep migrations the single source of truth (see CLAUDE.md
-- non-negotiable #8) and prevent that class of drift recurring.
--
-- document_type / document_rule seeding will land with M4.
-- ============================================================
