"""Generate the CP3 mass copy migrations from Roman's committed CSVs.

Usage:  python scripts/generate_cp3_copy.py <prod_state.json>
        (prod_state.json = dump of questionnaire content at generation time,
         produced by a one-off read-only dump script; needed to target rows by
         fixed question/option id and to hard-verify CSV Translations against
         live prompts.)

Outputs:
  supabase/migrations/20260711000002_cp3_copy_berlin.sql
  supabase/migrations/20260711000003_cp3_copy_essen.sql (incl. umlaut sweep)

Rules encoded here (see docs/milestone-log.md, content pass 3):
- Column "Copy New" -> prompt_de verbatim; "Sample Answer" -> validation.placeholder_de
  (merged into the validation JSONB, never clobbering other keys).
- Remaps by CSV row ID where the CSV key doesn't equal the live key (verified by
  Translation == target live prompt in Phase 1).
- Prompt-skip for keys whose prompt the structural migration owns (docx overrides);
  their placeholders still apply.
- Full-skip for rows targeting questions the structural migration deletes, and
  for non-question rows.
- Hard assertion: every applied row's Translation must match the live prompt
  (whitespace/'?' normalized), except the documented stale-Translation row B84.
- Essen umlaut sweep (D2): ae/oe/ue -> ä/ö/ü on user-visible Essen strings not
  covered by a CSV row; protected words (e.g. "aktuell") excluded; ss -> ß only
  for "Niessbrauch". Option VALUES are never touched — only label_de.
"""

import csv
import json
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATE = sys.argv[1]
S = json.load(open(STATE, encoding="utf-8"))

BERLIN = "30000000-0000-0000-0000-000000000001"
ESSEN = "30000000-0000-0000-0000-000000000003"
cat_qnn = {c["id"]: c["questionnaire_id"] for c in S["cats"]}
live = {BERLIN: {}, ESSEN: {}}
for q in S["questions"]:
    qn = cat_qnn.get(q["category_id"])
    if qn in live:
        live[qn][q["key"]] = q

REMAP = {  # (questionnaire, CSV row ID) -> live key
    (BERLIN, "24"): "disablity_card_application",   # DB key typo (CSV corrected it)
    (BERLIN, "25"): "disability_card_expiry",       # CSV key typo
    (BERLIN, "90"): "automobile_owner",
    (BERLIN, "94"): "automobile_holder",
    (BERLIN, "124"): "spouse_disability_card_expiry",
    (BERLIN, "151"): "spouse_automobile_owner",
    (BERLIN, "155"): "spouse_automobile_holder",
    (ESSEN, "210"): "spouse_applicant_bulk_topics",
}
STALE_TRANSLATION_OK = {(BERLIN, "84")}  # bank_savings_iban — Translation predates FP2; key correct
PROMPT_SKIP = {  # structural migration owns the prompt; placeholder still applies
    (BERLIN, "rent_debt"), (ESSEN, "former_rent_debt"),
    (ESSEN, "health_insurance_member_since"), (ESSEN, "spouse_health_insurance_member_since"),
}
FULL_SKIP_KEYS = {  # deleted by the structural migration / not questions
    "maintenance_bulk_topics", "cash_savings_yes_no", "spouse_cash_savings_yes_no",
    "funeral_insurance_due_date", "spouse_funeral_insurance_due_date",
    "care_facility_id", "social_office", "last_residence_plz",
}

def norm(s):
    return " ".join((s or "").split()).rstrip("?").strip().lower()

def sq(s):
    return "'" + str(s).replace("'", "''") + "'"

def gen(qnn, csv_name, out_name, title):
    rows = list(csv.DictReader(open(os.path.join(REPO, "docs", "content", csv_name), encoding="utf-8-sig")))
    L = [f"-- Content pass 3 — {title} (GENERATED by scripts/generate_cp3_copy.py from",
         f"-- docs/content/{csv_name}; do not hand-edit — re-run the generator).",
         "", "BEGIN;", ""]
    n_prompt = n_ph = 0
    for r in rows:
        rid, key = r["ID"], (r["Question"] or "").strip()
        key = REMAP.get((qnn, rid), key)
        if key in FULL_SKIP_KEYS:
            continue
        copy_new = (r["Copy New"] or "").strip()
        sample = (r["Sample Answer"] or "").strip()
        q = live[qnn].get(key)
        assert q, f"row {rid}: no live question {key!r}"
        if (qnn, rid) not in STALE_TRANSLATION_OK:
            assert norm(r["Translation"]) == norm(q["prompt_de"]), \
                f"row {rid} ({key}): Translation mismatch\n  csv:  {r['Translation']!r}\n  live: {q['prompt_de']!r}"
        if copy_new and (qnn, key) not in PROMPT_SKIP:
            L.append(f"UPDATE public.question SET prompt_de = {sq(copy_new)} WHERE id = '{q['id']}';  -- {key}")
            n_prompt += 1
        if sample:
            L.append(f"UPDATE public.question SET validation = COALESCE(validation, '{{}}'::jsonb) || "
                     f"jsonb_build_object('placeholder_de', {sq(sample)}) WHERE id = '{q['id']}';  -- {key} placeholder")
            n_ph += 1
    return rows, L, n_prompt, n_ph

# ── Berlin ─────────────────────────────────────────────────────────────────────
_, L, np_, nph = gen(BERLIN, "berlin_hzp_copy_changes.csv", None, "Berlin copy updates")
L += ["", "COMMIT;", ""]
open(os.path.join(REPO, "supabase", "migrations", "20260711000002_cp3_copy_berlin.sql"), "w",
     encoding="utf-8", newline="\n").write("\n".join(L))
print(f"berlin: {np_} prompts, {nph} placeholders")

# ── Essen (copy + umlaut sweep) ───────────────────────────────────────────────
rows, L, np_, nph = gen(ESSEN, "essen_hzp_copy_changes.csv", None, "Essen copy updates + umlaut sweep (D2)")

PROTECTED = ("aktuell", "Aktuell")
def deum(s):
    guard = {w: f"\x00{i}\x00" for i, w in enumerate(PROTECTED)}
    for w, t in guard.items():
        s = s.replace(w, t)
    s = re.sub(r"(?<![aeoqAEOQ])ue", "ü", s)
    s = re.sub(r"(?<![aeoqAEOQ])Ue", "Ü", s)
    s = re.sub(r"ae", "ä", s)
    s = re.sub(r"Ae", "Ä", s)
    s = re.sub(r"(?<![oO])oe", "ö", s)
    s = re.sub(r"Oe", "Ö", s)
    s = s.replace("Niessbrauch", "Nießbrauch")
    for w, t in guard.items():
        s = s.replace(t, w)
    return s

csv_covered = set()
for r in rows:
    k = REMAP.get((ESSEN, r["ID"]), (r["Question"] or "").strip())
    if (r["Copy New"] or "").strip():
        csv_covered.add(k)
DELETED = {"maintenance_bulk_topics", "cash_savings_yes_no", "spouse_cash_savings_yes_no",
           "funeral_insurance_due_date", "spouse_funeral_insurance_due_date",
           "home_contents_insurance_amount", "spouse_home_contents_insurance_amount"}
L.append("")
L.append("-- ── Umlaut sweep (D2): labels/prompts only; option VALUES untouched ─────────")
n_sw = 0
for q in S["questions"]:
    if cat_qnn.get(q["category_id"]) != ESSEN or q["key"] in csv_covered or q["key"] in DELETED:
        continue
    a = deum(q["prompt_de"])
    if a != q["prompt_de"]:
        L.append(f"UPDATE public.question SET prompt_de = {sq(a)} WHERE id = '{q['id']}';  -- sweep {q['key']}")
        n_sw += 1
qids_essen = {q["id"] for q in S["questions"] if cat_qnn.get(q["category_id"]) == ESSEN and q["key"] not in DELETED}
# Options the STRUCTURAL migration owns (reworded or deleted) — the sweep must
# not re-apply their pre-CP3 labels (D9's new label would be clobbered).
STRUCTURAL_OPTS = {
    ("61000000-0000-0000-0000-000000000017", "o1"),  # applicant bulk: D9 reword
    ("61000000-0000-0000-0000-000000000017", "o3"),  # applicant bulk: D9 delete
    ("61000000-0000-0000-0000-000000000055", "o4"),  # expense bulk: D6 delete
    ("61000000-0000-0000-0000-0000000000f3", "o4"),  # spouse expense bulk: D6 delete
    ("61000000-0000-0000-0000-000000000078", "o8"),  # wealth bulk: D8 delete
    ("61000000-0000-0000-0000-0000000000f4", "o8"),  # spouse wealth bulk: D8 delete
}
for o in S["options"]:
    if o["question_id"] not in qids_essen or (o["question_id"], o["key"]) in STRUCTURAL_OPTS:
        continue
    a = deum(o["label_de"])
    if a != o["label_de"]:
        L.append(f"UPDATE public.question_option SET label_de = {sq(a)} WHERE id = '{o['id']}';  -- sweep option")
        n_sw += 1
for g in S["groups"]:
    if cat_qnn.get(g["category_id"]) != ESSEN:
        continue
    for f in ("label_de", "custom_prompt_de"):
        v = g.get(f)
        if v and deum(v) != v:
            L.append(f"UPDATE public.question_group SET {f} = {sq(deum(v))} WHERE id = '{g['id']}';  -- sweep group")
            n_sw += 1
L += ["", "COMMIT;", ""]
open(os.path.join(REPO, "supabase", "migrations", "20260711000003_cp3_copy_essen.sql"), "w",
     encoding="utf-8", newline="\n").write("\n".join(L))
print(f"essen: {np_} prompts, {nph} placeholders, {n_sw} umlaut sweeps")
