"""Generate the M5 document catalog + Pankow rules seed migration from the
committed master (docs/content/pankow_document_rules_cto_master.xlsx).

Usage:  python scripts/generate_pankow_rules_seed.py
Output: supabase/migrations/20260711000006_m5r2_document_rules.sql

Seed-time transforms (decisions D3/D8, milestone log "M5"):
- Key map: general_liability_insurance_yes_no -> live "liablity" spelling (both
  persons); automobile_yes_no -> automobile_owner (both) — live keys are never
  renamed.
- PAN-026/027: free-text `citizenship not_equals "deutsch"` re-targeted to the
  D3 gates `german_citizenship_yes_no equals "Nein"` (exact match, no fuzzy
  text comparison).
Hard-asserts: every condition field maps to a live Berlin key or a D2/D3 key,
every repeat_for_each binding is known to lib/document-rules.ts, catalog/rule
referential integrity, counts 30/50.
"""

import json
import os
import re
import sys

import openpyxl

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "supabase", "migrations", "20260711000006_m5r2_document_rules.sql")

KEY_MAP = {
    "general_liability_insurance_yes_no": "general_liablity_insurance_yes_no",
    "spouse_general_liability_insurance_yes_no": "spouse_general_liablity_insurance_yes_no",
    "automobile_yes_no": "automobile_owner",
    "spouse_automobile_yes_no": "spouse_automobile_owner",
}
# D3 re-targets (field-level rewrite incl. operator+value)
D3_RETARGET = {
    "citizenship": {"field": "german_citizenship_yes_no", "operator": "equals", "value": "Nein"},
    "spouse_citizenship": {"field": "spouse_german_citizenship_yes_no", "operator": "equals", "value": "Nein"},
}
KNOWN_BINDINGS = {"applicant_bank_account", "spouse_bank_account", "pension_type",
                  "spouse_pension_type", "other_income", "spouse_other_income"}
# Keys that exist after Round 1 (D2/D3) — accepted by the field assertion.
ROUND1_KEYS = {"german_citizenship_yes_no", "spouse_german_citizenship_yes_no",
               "spouse_bank_giro", "spouse_bank_giro_blz", "spouse_bank_giro_iban",
               "spouse_bank_savings_account_yes_no", "spouse_bank_savings_iban",
               "spouse_bank_additional_account_yes_no", "spouse_bank_additional_name",
               "spouse_bank_additional_iban", "spouse_bank_additional_amount"}

PANKOW_OFFICE_ID = "11000000-0000-0000-0000-000000000001"  # created in 20260711000005


def transform(cond):
    if not isinstance(cond, dict):
        return cond
    out = {}
    for k, v in cond.items():
        if k in ("any", "all"):
            out[k] = [transform(c) for c in v]
        elif k == "field":
            if v in D3_RETARGET:
                return dict(D3_RETARGET[v])  # replaces the whole leaf
            out[k] = KEY_MAP.get(v, v)
        else:
            out[k] = v
    return out


def walk_fields(cond):
    if not isinstance(cond, dict):
        return
    if "field" in cond:
        yield cond["field"]
    for k in ("any", "all"):
        for c in cond.get(k, []):
            yield from walk_fields(c)


def walk_bindings(cond):
    if not isinstance(cond, dict):
        return
    if "repeat_for_each" in cond:
        yield cond["repeat_for_each"]
    for k in ("any", "all"):
        for c in cond.get(k, []):
            yield from walk_bindings(c)


def sq(s):
    return "NULL" if s is None else "'" + str(s).replace("'", "''") + "'"


wb = openpyxl.load_workbook(os.path.join(REPO, "docs", "content", "pankow_document_rules_cto_master.xlsx"), data_only=True)


def rows_of(sheet):
    rows = list(wb[sheet].iter_rows(values_only=True))
    hdr = [str(c).strip() for c in rows[0] if c is not None]
    return [dict(zip(hdr, [str(c).strip() if c is not None else None for c in r]))
            for r in rows[1:] if any(c is not None for c in r)]


catalog = rows_of("Document Catalog")
rules = rows_of("Pankow Rules")
assert len(catalog) == 30 and len(rules) == 50, (len(catalog), len(rules))
cat_ids = {c["document_id"] for c in catalog}

# live Berlin keys for the field assertion (from the M5 dump refreshed post-Round-1
# is ideal, but the pre-Round-1 dump + ROUND1_KEYS covers the same set)
S = json.load(open(os.path.join(os.environ.get("M5_STATE_DIR", "."), "prod_state_m5.json"), encoding="utf-8")) \
    if os.path.exists(os.path.join(os.environ.get("M5_STATE_DIR", "."), "prod_state_m5.json")) else None
live_keys = set()
if S:
    B = "30000000-0000-0000-0000-000000000001"
    catq = {c["id"]: c["questionnaire_id"] for c in S["cats"]}
    live_keys = {q["key"] for q in S["questions"] if catq.get(q["category_id"]) == B}

L = ["-- M5 Round 2 — document catalog + Pankow rules seed (GENERATED by",
     "-- scripts/generate_pankow_rules_seed.py from docs/content/",
     "-- pankow_document_rules_cto_master.xlsx; do not hand-edit).",
     "-- Roman's DOC-#### / PAN-### ids are the primary keys. Conditions are the",
     "-- master's condition_json with the seed-time key map + D3 re-targets applied.",
     "", "BEGIN;", "",
     "INSERT INTO public.document_catalog (id, technical_key, name_de, category, instance_basis, active) VALUES"]
lines = []
for c in catalog:
    lines.append(f"  ({sq(c['document_id'])}, {sq(c['technical_key'])}, {sq(c['user_facing_name_de'])}, "
                 f"{sq(c['category'])}, {sq(c['default_instance_basis'])}, {str(c['active'] == 'True').lower()})")
L.append(",\n".join(lines))
L.append("ON CONFLICT (id) DO NOTHING;")
L.append("")
L.append("INSERT INTO public.office_document_rule (id, social_office_id, document_id, requirement_type, subject, instance_note, period_months, condition) VALUES")
lines = []
for r in rules:
    assert r["document_id"] in cat_ids, r["rule_id"]
    cond = transform(json.loads(r["condition_json"])) if r["condition_json"] else {"always": True}
    for f in walk_fields(cond):
        assert (not live_keys) or f in live_keys or f in ROUND1_KEYS, f"{r['rule_id']}: unknown field {f!r}"
    for b in walk_bindings(cond):
        assert b in KNOWN_BINDINGS, f"{r['rule_id']}: unknown binding {b!r}"
    assert r["requirement_type"] in ("mandatory", "conditional"), r["rule_id"]
    assert r["subject"] in ("person_1", "person_2", "previous_home"), r["rule_id"]
    pm = r["period_months"]
    pm_sql = pm if pm and pm != "None" else "NULL"
    cj = json.dumps(cond, ensure_ascii=False).replace("'", "''")
    lines.append(f"  ({sq(r['rule_id'])}, '{PANKOW_OFFICE_ID}', {sq(r['document_id'])}, {sq(r['requirement_type'])}, "
                 f"{sq(r['subject'])}, {sq(r['instance_rule'])}, {pm_sql}, '{cj}'::jsonb)")
L.append(",\n".join(lines))
L.append("ON CONFLICT (id) DO NOTHING;")
L += ["", "COMMIT;", ""]
open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(L))
print(f"WROTE {OUT}: catalog=30 rules=50 (field assertions {'ON' if live_keys else 'OFF — no state file'})")
