-- GENERATED (feedback pass item 3): Pankow rules made Essen-compatible.
-- 19 marital any-blocks gain {field: marital_status, equals 'Lebenspartnerschaft'}
-- (Essen's option value; Berlin has no such option value -> inert there).
-- PAN-020 gains equals branches for Essen's two life-insurance option values.
-- PAN-022 EXCLUDED: funeral_insurance_yes_no exists in Berlin too (stop rule).

BEGIN;

UPDATE public.office_document_rule SET condition = '{"any": [{"field": "marital_status", "value": "verheiratet", "operator": "equals"}, {"field": "marital_status", "value": "eingetragene Lebenspartnerschaft", "operator": "equals"}, {"field": "marital_status", "value": "eheähnliche Gemeinschaft", "operator": "equals"}, {"field": "marital_status", "operator": "equals", "value": "Lebenspartnerschaft"}]}'::jsonb WHERE id = 'PAN-002';
UPDATE public.office_document_rule SET condition = '{"all": [{"any": [{"field": "marital_status", "value": "verheiratet", "operator": "equals"}, {"field": "marital_status", "value": "eingetragene Lebenspartnerschaft", "operator": "equals"}, {"field": "marital_status", "value": "eheähnliche Gemeinschaft", "operator": "equals"}, {"field": "marital_status", "operator": "equals", "value": "Lebenspartnerschaft"}]}, {"repeat_for_each": "spouse_pension_type"}]}'::jsonb WHERE id = 'PAN-004';
UPDATE public.office_document_rule SET condition = '{"all": [{"any": [{"field": "marital_status", "value": "verheiratet", "operator": "equals"}, {"field": "marital_status", "value": "eingetragene Lebenspartnerschaft", "operator": "equals"}, {"field": "marital_status", "value": "eheähnliche Gemeinschaft", "operator": "equals"}, {"field": "marital_status", "operator": "equals", "value": "Lebenspartnerschaft"}]}, {"period_months": 4, "repeat_for_each": "spouse_bank_account"}]}'::jsonb WHERE id = 'PAN-006';
UPDATE public.office_document_rule SET condition = '{"any": [{"field": "marital_status", "value": "verheiratet", "operator": "equals"}, {"field": "marital_status", "value": "eingetragene Lebenspartnerschaft", "operator": "equals"}, {"field": "marital_status", "value": "eheähnliche Gemeinschaft", "operator": "equals"}, {"field": "marital_status", "operator": "equals", "value": "Lebenspartnerschaft"}]}'::jsonb WHERE id = 'PAN-011';
UPDATE public.office_document_rule SET condition = '{"all": [{"any": [{"field": "marital_status", "value": "verheiratet", "operator": "equals"}, {"field": "marital_status", "value": "eingetragene Lebenspartnerschaft", "operator": "equals"}, {"field": "marital_status", "value": "eheähnliche Gemeinschaft", "operator": "equals"}, {"field": "marital_status", "operator": "equals", "value": "Lebenspartnerschaft"}]}, {"field": "spouse_in_facility_yes_no", "value": "Ja", "operator": "equals"}]}'::jsonb WHERE id = 'PAN-013';
UPDATE public.office_document_rule SET condition = '{"all": [{"any": [{"field": "marital_status", "value": "verheiratet", "operator": "equals"}, {"field": "marital_status", "value": "eingetragene Lebenspartnerschaft", "operator": "equals"}, {"field": "marital_status", "value": "eheähnliche Gemeinschaft", "operator": "equals"}, {"field": "marital_status", "operator": "equals", "value": "Lebenspartnerschaft"}]}, {"field": "spouse_in_facility_yes_no", "value": "Ja", "operator": "equals"}]}'::jsonb WHERE id = 'PAN-015';
UPDATE public.office_document_rule SET condition = '{"all": [{"any": [{"field": "marital_status", "value": "verheiratet", "operator": "equals"}, {"field": "marital_status", "value": "eingetragene Lebenspartnerschaft", "operator": "equals"}, {"field": "marital_status", "value": "eheähnliche Gemeinschaft", "operator": "equals"}, {"field": "marital_status", "operator": "equals", "value": "Lebenspartnerschaft"}]}, {"field": "spouse_life_insurance", "value": "Lebensversicherung", "operator": "equals"}]}'::jsonb WHERE id = 'PAN-021';
UPDATE public.office_document_rule SET condition = '{"all": [{"any": [{"field": "marital_status", "value": "verheiratet", "operator": "equals"}, {"field": "marital_status", "value": "eingetragene Lebenspartnerschaft", "operator": "equals"}, {"field": "marital_status", "value": "eheähnliche Gemeinschaft", "operator": "equals"}, {"field": "marital_status", "operator": "equals", "value": "Lebenspartnerschaft"}]}, {"field": "spouse_life_insurance", "value": "Sterbeversicherung", "operator": "equals"}]}'::jsonb WHERE id = 'PAN-023';
UPDATE public.office_document_rule SET condition = '{"all": [{"any": [{"field": "marital_status", "value": "verheiratet", "operator": "equals"}, {"field": "marital_status", "value": "eingetragene Lebenspartnerschaft", "operator": "equals"}, {"field": "marital_status", "value": "eheähnliche Gemeinschaft", "operator": "equals"}, {"field": "marital_status", "operator": "equals", "value": "Lebenspartnerschaft"}]}, {"field": "spouse_german_citizenship_yes_no", "value": "Nein", "operator": "equals"}]}'::jsonb WHERE id = 'PAN-027';
UPDATE public.office_document_rule SET condition = '{"all": [{"any": [{"field": "marital_status", "value": "verheiratet", "operator": "equals"}, {"field": "marital_status", "value": "eingetragene Lebenspartnerschaft", "operator": "equals"}, {"field": "marital_status", "value": "eheähnliche Gemeinschaft", "operator": "equals"}, {"field": "marital_status", "operator": "equals", "value": "Lebenspartnerschaft"}]}, {"field": "spouse_disability_card", "value": "Ja", "operator": "equals"}]}'::jsonb WHERE id = 'PAN-029';
UPDATE public.office_document_rule SET condition = '{"all": [{"any": [{"field": "marital_status", "value": "verheiratet", "operator": "equals"}, {"field": "marital_status", "value": "eingetragene Lebenspartnerschaft", "operator": "equals"}, {"field": "marital_status", "value": "eheähnliche Gemeinschaft", "operator": "equals"}, {"field": "marital_status", "operator": "equals", "value": "Lebenspartnerschaft"}]}, {"field": "spouse_general_liablity_insurance_yes_no", "value": "Ja", "operator": "equals"}]}'::jsonb WHERE id = 'PAN-031';
UPDATE public.office_document_rule SET condition = '{"all": [{"any": [{"field": "marital_status", "value": "verheiratet", "operator": "equals"}, {"field": "marital_status", "value": "eingetragene Lebenspartnerschaft", "operator": "equals"}, {"field": "marital_status", "value": "eheähnliche Gemeinschaft", "operator": "equals"}, {"field": "marital_status", "operator": "equals", "value": "Lebenspartnerschaft"}]}, {"field": "spouse_wohngeld_yes_no", "value": "Ja", "operator": "equals"}]}'::jsonb WHERE id = 'PAN-033';
UPDATE public.office_document_rule SET condition = '{"all": [{"any": [{"field": "marital_status", "value": "verheiratet", "operator": "equals"}, {"field": "marital_status", "value": "eingetragene Lebenspartnerschaft", "operator": "equals"}, {"field": "marital_status", "value": "eheähnliche Gemeinschaft", "operator": "equals"}, {"field": "marital_status", "operator": "equals", "value": "Lebenspartnerschaft"}]}, {"field": "spouse_special_origin_rights", "value": "Nein", "operator": "not_equals"}]}'::jsonb WHERE id = 'PAN-035';
UPDATE public.office_document_rule SET condition = '{"all": [{"any": [{"field": "marital_status", "value": "verheiratet", "operator": "equals"}, {"field": "marital_status", "value": "eingetragene Lebenspartnerschaft", "operator": "equals"}, {"field": "marital_status", "value": "eheähnliche Gemeinschaft", "operator": "equals"}, {"field": "marital_status", "operator": "equals", "value": "Lebenspartnerschaft"}]}, {"any": [{"field": "spouse_prior_social_aid", "value": "Ja", "operator": "equals"}, {"field": "spouse_prior_social_service_applications", "value": "Ja", "operator": "equals"}]}]}'::jsonb WHERE id = 'PAN-038';
UPDATE public.office_document_rule SET condition = '{"all": [{"any": [{"field": "marital_status", "value": "verheiratet", "operator": "equals"}, {"field": "marital_status", "value": "eingetragene Lebenspartnerschaft", "operator": "equals"}, {"field": "marital_status", "value": "eheähnliche Gemeinschaft", "operator": "equals"}, {"field": "marital_status", "operator": "equals", "value": "Lebenspartnerschaft"}]}, {"when": {"field": "spouse_other_income", "value": "Ja", "operator": "equals"}, "repeat_for_each": "spouse_other_income"}]}'::jsonb WHERE id = 'PAN-042';
UPDATE public.office_document_rule SET condition = '{"all": [{"any": [{"field": "marital_status", "value": "verheiratet", "operator": "equals"}, {"field": "marital_status", "value": "eingetragene Lebenspartnerschaft", "operator": "equals"}, {"field": "marital_status", "value": "eheähnliche Gemeinschaft", "operator": "equals"}, {"field": "marital_status", "operator": "equals", "value": "Lebenspartnerschaft"}]}, {"field": "spouse_automobile_owner", "value": "Ja", "operator": "equals"}]}'::jsonb WHERE id = 'PAN-044';
UPDATE public.office_document_rule SET condition = '{"all": [{"any": [{"field": "marital_status", "value": "verheiratet", "operator": "equals"}, {"field": "marital_status", "value": "eingetragene Lebenspartnerschaft", "operator": "equals"}, {"field": "marital_status", "value": "eheähnliche Gemeinschaft", "operator": "equals"}, {"field": "marital_status", "operator": "equals", "value": "Lebenspartnerschaft"}]}, {"field": "spouse_automobile_owner", "value": "Ja", "operator": "equals"}]}'::jsonb WHERE id = 'PAN-046';
UPDATE public.office_document_rule SET condition = '{"all": [{"any": [{"field": "marital_status", "value": "verheiratet", "operator": "equals"}, {"field": "marital_status", "value": "eingetragene Lebenspartnerschaft", "operator": "equals"}, {"field": "marital_status", "value": "eheähnliche Gemeinschaft", "operator": "equals"}, {"field": "marital_status", "operator": "equals", "value": "Lebenspartnerschaft"}]}, {"field": "spouse_automobile_owner", "value": "Ja", "operator": "equals"}]}'::jsonb WHERE id = 'PAN-048';
UPDATE public.office_document_rule SET condition = '{"all": [{"any": [{"field": "marital_status", "value": "verheiratet", "operator": "equals"}, {"field": "marital_status", "value": "eingetragene Lebenspartnerschaft", "operator": "equals"}, {"field": "marital_status", "value": "eheähnliche Gemeinschaft", "operator": "equals"}, {"field": "marital_status", "operator": "equals", "value": "Lebenspartnerschaft"}]}, {"field": "spouse_property_yes_no", "value": "Nein", "operator": "not_equals"}]}'::jsonb WHERE id = 'PAN-050';
UPDATE public.office_document_rule SET condition = '{"any": [{"field": "life_insurance", "operator": "equals", "value": "Lebensversicherung"}, {"field": "life_insurance", "operator": "equals", "value": "Kapitallebensversicherung"}, {"field": "life_insurance", "operator": "equals", "value": "Risikolebensversicherung"}]}'::jsonb WHERE id = 'PAN-020';

COMMIT;
