-- Content pass 3 — Essen copy updates + umlaut sweep (D2) (GENERATED by scripts/generate_cp3_copy.py from
-- docs/content/essen_hzp_copy_changes.csv; do not hand-edit — re-run the generator).

BEGIN;

UPDATE public.question SET prompt_de = 'Welche Staatsangehörigkeit haben Sie?' WHERE id = '61000000-0000-0000-0000-00000000000d';  -- citizenship
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'deutsch') WHERE id = '61000000-0000-0000-0000-00000000000d';  -- citizenship placeholder
UPDATE public.question SET prompt_de = 'Welchen Aufenthaltsstatus haben Sie?' WHERE id = '61000000-0000-0000-0000-00000000000e';  -- residence_status
UPDATE public.question SET prompt_de = 'Wann sind Sie nach Deutschland eingereist?' WHERE id = '61000000-0000-0000-0000-00000000000f';  -- entry_to_germany_date
UPDATE public.question SET prompt_de = 'Welchen sonstigen Aufenthaltsstatus haben Sie?' WHERE id = '61000000-0000-0000-0000-000000000010';  -- residence_status_other
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Niederlassungserlaubnis') WHERE id = '61000000-0000-0000-0000-000000000010';  -- residence_status_other placeholder
UPDATE public.question SET prompt_de = 'Haben Sie eine gesetzliche Betreuung oder eine bevollmächtigte Person?' WHERE id = '61000000-0000-0000-0000-000000000011';  -- legal_guardian_yes_no
UPDATE public.question SET prompt_de = 'Wie heißt Ihre Betreuung oder bevollmächtigte Person, und wie ist die Adresse?' WHERE id = '61000000-0000-0000-0000-000000000012';  -- legal_guardian_name_address
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Max Mustermann, Musterstraße 12') WHERE id = '61000000-0000-0000-0000-000000000012';  -- legal_guardian_name_address placeholder
UPDATE public.question SET prompt_de = 'Haben Sie einen Schwerbehindertenausweis oder Feststellungsbescheid?' WHERE id = '61000000-0000-0000-0000-000000000013';  -- disability_card
UPDATE public.question SET prompt_de = 'Bis wann ist Ihr Schwerbehindertenausweis oder Feststellungsbescheid gültig?' WHERE id = '61000000-0000-0000-0000-000000000014';  -- disability_card_expiry
UPDATE public.question SET prompt_de = 'Wann haben Sie den Schwerbehindertenausweis oder Feststellungsbescheid beantragt?' WHERE id = '61000000-0000-0000-0000-000000000015';  -- disability_card_application_date
UPDATE public.question SET prompt_de = 'Welche Merkzeichen stehen in Ihrem Schwerbehindertenausweis?' WHERE id = '61000000-0000-0000-0000-000000000016';  -- disability_card_markers
UPDATE public.question SET prompt_de = 'Trifft eine dieser seltenen Situationen auf Sie zu?' WHERE id = '61000000-0000-0000-0000-000000000017';  -- applicant_bulk_topics
UPDATE public.question SET prompt_de = 'Wann hat jemand bei der Ausländerbehörde unterschrieben, finanziell für Sie einzustehen?' WHERE id = '61000000-0000-0000-0000-000000000018';  -- commitment_declaration_date
UPDATE public.question SET prompt_de = 'Von welcher Stelle haben Sie diese Leistungen bekommen?' WHERE id = '61000000-0000-0000-0000-000000000019';  -- prior_sgb_benefits_provider
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Jobcenter Essen') WHERE id = '61000000-0000-0000-0000-000000000019';  -- prior_sgb_benefits_provider placeholder
UPDATE public.question SET prompt_de = 'Seit wann haben Sie diese Leistungen bekommen?' WHERE id = '61000000-0000-0000-0000-00000000001a';  -- prior_sgb_benefits_from
UPDATE public.question SET prompt_de = 'Bis wann haben Sie diese Leistungen bekommen?' WHERE id = '61000000-0000-0000-0000-00000000001b';  -- prior_sgb_benefits_until
UPDATE public.question SET prompt_de = 'In welcher Straße lag Ihre letzte Wohnung?' WHERE id = '61000000-0000-0000-0000-00000000001c';  -- last_residence_street
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Musterstraße') WHERE id = '61000000-0000-0000-0000-00000000001c';  -- last_residence_street placeholder
UPDATE public.question SET prompt_de = 'Wie lautete die Hausnummer Ihrer letzten Wohnung?' WHERE id = '61000000-0000-0000-0000-00000000001d';  -- last_residence_house_number
UPDATE public.question SET prompt_de = 'In welchem Ort lag Ihre letzte Wohnung?' WHERE id = '61000000-0000-0000-0000-00000000001f';  -- last_residence_city
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Essen') WHERE id = '61000000-0000-0000-0000-00000000001f';  -- last_residence_city placeholder
UPDATE public.question SET prompt_de = 'Hatten Sie vor dem Einzug ins Pflegeheim eine Mietwohnung?' WHERE id = '61000000-0000-0000-0000-000000000020';  -- former_rental_apartment_yes_no
UPDATE public.question SET prompt_de = 'Läuft der Mietvertrag Ihrer letzten Wohnung noch?' WHERE id = '61000000-0000-0000-0000-000000000021';  -- former_rent_contract_active_yes_no
UPDATE public.question SET prompt_de = 'Bis wann wurde die Miete für Ihre letzte Wohnung bezahlt?' WHERE id = '61000000-0000-0000-0000-000000000023';  -- former_rent_paid_until
UPDATE public.question SET prompt_de = 'Haben Sie Ihre letzte Wohnung bereits gekündigt?' WHERE id = '61000000-0000-0000-0000-000000000024';  -- former_rent_contract_termination_yes_no
UPDATE public.question SET prompt_de = 'Zu welchem Datum wurde Ihre letzte Wohnung gekündigt?' WHERE id = '61000000-0000-0000-0000-000000000025';  -- former_rent_contract_terminated_by
UPDATE public.question SET prompt_de = 'Wie heißen Ihr Vermieter und seine Adresse?' WHERE id = '61000000-0000-0000-0000-000000000027';  -- former_landlord_name_address
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Hausverwaltung Müller, Musterstraße 12') WHERE id = '61000000-0000-0000-0000-000000000027';  -- former_landlord_name_address placeholder
UPDATE public.question SET prompt_de = 'Glauben Sie, dass dieses Kind 100.000 Euro oder mehr im Jahr verdient?' WHERE id = '61000000-0000-0000-0000-000000000028';  -- child_high_income_100k_yes_no
UPDATE public.question SET prompt_de = 'Welchen Familienstand hat Ihr Kind?' WHERE id = '61000000-0000-0000-0000-00000000002d';  -- child_marital_status
UPDATE public.question SET prompt_de = 'In welchem Verhältnis steht dieses Kind zu Ihnen?' WHERE id = '61000000-0000-0000-0000-00000000002e';  -- child_family_tie
UPDATE public.question SET prompt_de = 'Welchen Beruf hat Ihr Kind?' WHERE id = '61000000-0000-0000-0000-00000000002f';  -- child_profession
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Kauffrau') WHERE id = '61000000-0000-0000-0000-00000000002f';  -- child_profession placeholder
UPDATE public.question SET prompt_de = 'Wie lautet der Vorname Ihres getrennt lebenden oder geschiedenen Partners?' WHERE id = '61000000-0000-0000-0000-000000000032';  -- ex_partner_first_name
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Max') WHERE id = '61000000-0000-0000-0000-000000000032';  -- ex_partner_first_name placeholder
UPDATE public.question SET prompt_de = 'Wie lautet der Nachname Ihres getrennt lebenden oder geschiedenen Partners?' WHERE id = '61000000-0000-0000-0000-000000000033';  -- ex_partner_last_name
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Mustermann') WHERE id = '61000000-0000-0000-0000-000000000033';  -- ex_partner_last_name placeholder
UPDATE public.question SET prompt_de = 'In welcher Straße wohnt Ihr getrennt lebender oder geschiedener Partner?' WHERE id = '61000000-0000-0000-0000-000000000034';  -- ex_partner_street
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Musterstraße') WHERE id = '61000000-0000-0000-0000-000000000034';  -- ex_partner_street placeholder
UPDATE public.question SET prompt_de = 'Wie lautet die Hausnummer Ihres getrennt lebenden oder geschiedenen Partners?' WHERE id = '61000000-0000-0000-0000-000000000035';  -- ex_partner_house_number
UPDATE public.question SET prompt_de = 'Wie lautet die Postleitzahl Ihres getrennt lebenden oder geschiedenen Partners?' WHERE id = '61000000-0000-0000-0000-000000000036';  -- ex_partner_plz
UPDATE public.question SET prompt_de = 'In welchem Ort wohnt Ihr getrennt lebender oder geschiedener Partner?' WHERE id = '61000000-0000-0000-0000-000000000037';  -- ex_partner_city
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Essen') WHERE id = '61000000-0000-0000-0000-000000000037';  -- ex_partner_city placeholder
UPDATE public.question SET prompt_de = 'Wann wurde Ihr getrennt lebender oder geschiedener Partner geboren?' WHERE id = '61000000-0000-0000-0000-000000000038';  -- ex_partner_birthdate
UPDATE public.question SET prompt_de = 'In welchem Ort wurde Ihr getrennt lebender oder geschiedener Partner geboren?' WHERE id = '61000000-0000-0000-0000-000000000039';  -- ex_partner_city_of_birth
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Bochum') WHERE id = '61000000-0000-0000-0000-000000000039';  -- ex_partner_city_of_birth placeholder
UPDATE public.question SET prompt_de = 'Wie sind Sie kranken- und pflegeversichert?' WHERE id = '61000000-0000-0000-0000-00000000003c';  -- health_insurance_type
UPDATE public.question SET prompt_de = 'Haben Sie eine ausländische Krankenversicherung?' WHERE id = '61000000-0000-0000-0000-000000000040';  -- foreign_health_insurance_yes_no
UPDATE public.question SET prompt_de = 'Wie heißen die ausländische Krankenversicherung und ihre Adresse?' WHERE id = '61000000-0000-0000-0000-000000000041';  -- foreign_health_insurance_name_address
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Mutuelle Santé, Rue de Paris 1') WHERE id = '61000000-0000-0000-0000-000000000041';  -- foreign_health_insurance_name_address placeholder
UPDATE public.question SET prompt_de = 'Ab wann waren Sie dort versichert?' WHERE id = '61000000-0000-0000-0000-000000000043';  -- last_health_insurance_from
UPDATE public.question SET prompt_de = 'Welche Rente oder Pension bekommen Sie?' WHERE id = '61000000-0000-0000-0000-000000000045';  -- pension_type
UPDATE public.question SET prompt_de = 'Wie hoch ist der Bruttobetrag dieser Rente oder Pension pro Monat?' WHERE id = '61000000-0000-0000-0000-000000000046';  -- pension_amount_gross
UPDATE public.question SET prompt_de = 'Wie hoch ist der Nettobetrag dieser Rente oder Pension pro Monat?' WHERE id = '61000000-0000-0000-0000-000000000047';  -- pension_amount
UPDATE public.question SET prompt_de = 'Haben Sie eine Rente beantragt, über die noch nicht entschieden wurde?' WHERE id = '61000000-0000-0000-0000-000000000048';  -- pension_application_yes_no
UPDATE public.question SET prompt_de = 'Wann haben Sie die Rente beantragt?' WHERE id = '61000000-0000-0000-0000-000000000049';  -- pension_application_date
UPDATE public.question SET prompt_de = 'Bei welcher Stelle haben Sie die Rente beantragt?' WHERE id = '61000000-0000-0000-0000-00000000004a';  -- pension_application_issuer
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Deutsche Rentenversicherung') WHERE id = '61000000-0000-0000-0000-00000000004a';  -- pension_application_issuer placeholder
UPDATE public.question SET prompt_de = 'Welche Versicherungsnummer gehört zu diesem Rentenantrag?' WHERE id = '61000000-0000-0000-0000-00000000004b';  -- pension_application_insurance_number
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', '12 010180 M 123') WHERE id = '61000000-0000-0000-0000-00000000004b';  -- pension_application_insurance_number placeholder
UPDATE public.question SET prompt_de = 'Welche Rente haben Sie beantragt?' WHERE id = '61000000-0000-0000-0000-00000000004c';  -- pension_application_type
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Altersrente') WHERE id = '61000000-0000-0000-0000-00000000004c';  -- pension_application_type placeholder
UPDATE public.question SET prompt_de = 'Haben Sie weiteres Einkommen?' WHERE id = '61000000-0000-0000-0000-00000000004d';  -- other_income
UPDATE public.question SET prompt_de = 'Welche Art von weiterem Einkommen haben Sie?' WHERE id = '61000000-0000-0000-0000-00000000004e';  -- other_income_type
UPDATE public.question SET prompt_de = 'Trifft eine dieser besonderen Einkommens- oder Rentensituationen auf Sie zu?' WHERE id = '61000000-0000-0000-0000-000000000050';  -- income_bulk_topics
UPDATE public.question SET prompt_de = 'Wann haben Sie den Antrag nach dem Opferentschädigungsgesetz gestellt?' WHERE id = '61000000-0000-0000-0000-000000000051';  -- oeg_application_date
UPDATE public.question SET prompt_de = 'Bei welcher Stelle haben Sie den Antrag nach dem Opferentschädigungsgesetz gestellt?' WHERE id = '61000000-0000-0000-0000-000000000052';  -- oeg_application_issuer
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Versorgungsamt Essen') WHERE id = '61000000-0000-0000-0000-000000000052';  -- oeg_application_issuer placeholder
UPDATE public.question SET prompt_de = 'In welchem Land und in welchem Zeitraum wurden ausländische Rentenbeiträge gezahlt?' WHERE id = '61000000-0000-0000-0000-000000000053';  -- foreign_pension_contributions_details
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Türkei, 1975-1980') WHERE id = '61000000-0000-0000-0000-000000000053';  -- foreign_pension_contributions_details placeholder
UPDATE public.question SET prompt_de = 'Wann und wo haben Sie im Ausland gearbeitet, ohne Rentenbeiträge zu zahlen?' WHERE id = '61000000-0000-0000-0000-000000000054';  -- foreign_work_without_pension_contributions_details
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Türkei, 1975-1980, Firma Yilmaz, ca. 800 EUR/Monat') WHERE id = '61000000-0000-0000-0000-000000000054';  -- foreign_work_without_pension_contributions_details placeholder
UPDATE public.question SET prompt_de = 'Haben Sie eine dieser Ausgaben?' WHERE id = '61000000-0000-0000-0000-000000000055';  -- expense_bulk_topics
UPDATE public.question SET prompt_de = 'Wie hoch sind Ihre monatlichen Sozialversicherungsbeiträge?' WHERE id = '61000000-0000-0000-0000-000000000057';  -- social_security_contributions_amount
UPDATE public.question SET prompt_de = 'Wie hoch sind die monatlichen Altersvorsorgebeiträge?' WHERE id = '61000000-0000-0000-0000-00000000005b';  -- pension_contributions_amount
UPDATE public.question SET prompt_de = 'Wie viel Bargeld haben Sie?' WHERE id = '61000000-0000-0000-0000-00000000005e';  -- cash_savings_amount
UPDATE public.question SET prompt_de = 'Haben Sie Bankguthaben?' WHERE id = '61000000-0000-0000-0000-00000000005f';  -- bank_giro_yes_no
UPDATE public.question SET prompt_de = 'Haben Sie Sparguthaben?' WHERE id = '61000000-0000-0000-0000-000000000061';  -- bank_savings_account_yes_no
UPDATE public.question SET prompt_de = 'Haben Sie sonstige Kontoguthaben, z. B. PayPal?' WHERE id = '61000000-0000-0000-0000-000000000063';  -- bank_additional_account_yes_no
UPDATE public.question SET prompt_de = 'Haben Sie einen Bestattungsvorsorgevertrag?' WHERE id = '61000000-0000-0000-0000-000000000065';  -- funeral_insurance_yes_no
UPDATE public.question SET prompt_de = 'Wie hoch ist der Betrag des Bestattungsvorsorgevertrags?' WHERE id = '61000000-0000-0000-0000-000000000066';  -- funeral_insurance_amount
UPDATE public.question SET prompt_de = 'Wie hoch ist der aktuelle Rückkaufswert der Lebensversicherung?' WHERE id = '61000000-0000-0000-0000-00000000006a';  -- life_insurance_surrender_value
UPDATE public.question SET prompt_de = 'Haben Sie ein Kraftfahrzeug?' WHERE id = '61000000-0000-0000-0000-00000000006b';  -- automobile_yes_no
UPDATE public.question SET prompt_de = 'Welches amtliche Kennzeichen hat das Kraftfahrzeug?' WHERE id = '61000000-0000-0000-0000-00000000006c';  -- automobile_numbers_plate
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'E-AB 1234') WHERE id = '61000000-0000-0000-0000-00000000006c';  -- automobile_numbers_plate placeholder
UPDATE public.question SET prompt_de = 'Aus welchem Baujahr ist das Kraftfahrzeug?' WHERE id = '61000000-0000-0000-0000-00000000006d';  -- automobile_year
UPDATE public.question SET prompt_de = 'Welches Fahrzeugmodell ist es?' WHERE id = '61000000-0000-0000-0000-00000000006e';  -- automobile_type
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Golf') WHERE id = '61000000-0000-0000-0000-00000000006e';  -- automobile_type placeholder
UPDATE public.question SET prompt_de = 'Welches ist der Fahrzeugtyp?' WHERE id = '61000000-0000-0000-0000-00000000006f';  -- automobile_vehicle_type
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'VW') WHERE id = '61000000-0000-0000-0000-00000000006f';  -- automobile_vehicle_type placeholder
UPDATE public.question SET prompt_de = 'Bitte geben Sie Adresse, Art und Nutzung Ihres Haus- oder Wohneigentums an.' WHERE id = '61000000-0000-0000-0000-000000000072';  -- property_notes
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Eigentumswohnung, Musterstraße 12, vermietet') WHERE id = '61000000-0000-0000-0000-000000000072';  -- property_notes placeholder
UPDATE public.question SET prompt_de = 'Bitte geben Sie Adresse, Art und Nutzung Ihres sonstigen Grundbesitzes an.' WHERE id = '61000000-0000-0000-0000-000000000074';  -- additional_property_notes
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Garage, Musterstraße 12, vermietet') WHERE id = '61000000-0000-0000-0000-000000000074';  -- additional_property_notes placeholder
UPDATE public.question SET prompt_de = 'Haben Sie in den letzten 10 Jahren Vermögen an andere Personen übertragen?' WHERE id = '61000000-0000-0000-0000-000000000075';  -- asset_transfer_yes_no
UPDATE public.question SET prompt_de = 'Wann wurde das Vermögen übertragen?' WHERE id = '61000000-0000-0000-0000-000000000076';  -- asset_transfer_date
UPDATE public.question SET prompt_de = 'In welcher Höhe wurde Vermögen übertragen?' WHERE id = '61000000-0000-0000-0000-000000000077';  -- asset_transfer_amount
UPDATE public.question SET prompt_de = 'Haben Sie eine dieser besonderen Vermögensarten?' WHERE id = '61000000-0000-0000-0000-000000000078';  -- wealth_bulk_topics
UPDATE public.question SET prompt_de = 'Welchen Wert haben Ihr Schmuck oder Ihre Edelmetalle?' WHERE id = '61000000-0000-0000-0000-00000000007a';  -- jewelry_metals_amount
UPDATE public.question SET prompt_de = 'Welchen Wert hat Ihr sonstiges Vermögen?' WHERE id = '61000000-0000-0000-0000-00000000007b';  -- additional_wealth_amount
UPDATE public.question SET prompt_de = 'Welche Art von sonstigem Vermögen haben Sie?' WHERE id = '61000000-0000-0000-0000-00000000007c';  -- additional_wealth_type
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Schmuck') WHERE id = '61000000-0000-0000-0000-00000000007c';  -- additional_wealth_type placeholder
UPDATE public.question SET prompt_de = 'Wie hoch ist der Betrag Ihrer staatlich geförderten privaten Altersvorsorge?' WHERE id = '61000000-0000-0000-0000-00000000007d';  -- state_subsidized_private_pension_amount
UPDATE public.question SET prompt_de = 'Wann ist dieser Betrag fällig?' WHERE id = '61000000-0000-0000-0000-00000000007e';  -- state_subsidized_private_pension_due_date
UPDATE public.question SET prompt_de = 'Wie hoch ist der Betrag Ihrer sonstigen privaten Altersvorsorge?' WHERE id = '61000000-0000-0000-0000-00000000007f';  -- private_pension_amount
UPDATE public.question SET prompt_de = 'Wann ist dieser Betrag fällig?' WHERE id = '61000000-0000-0000-0000-000000000080';  -- private_pension_due_date
UPDATE public.question SET prompt_de = 'Haben Sie durch einen Vertrag noch Rechte an einem Haus, einer Wohnung oder einem Grundstück?' WHERE id = '61000000-0000-0000-0000-000000000083';  -- transfer_contract_claims_notes
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Ich darf weiterhin in der Wohnung wohnen') WHERE id = '61000000-0000-0000-0000-000000000083';  -- transfer_contract_claims_notes placeholder
UPDATE public.question SET prompt_de = 'Erwarten Sie eine Erbschaft oder haben Sie noch Anspruch auf etwas aus einer Erbschaft?' WHERE id = '61000000-0000-0000-0000-000000000084';  -- inheritance_claims_notes
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Erbe nach verstorbener Mutter noch nicht ausgezahlt') WHERE id = '61000000-0000-0000-0000-000000000084';  -- inheritance_claims_notes placeholder
UPDATE public.question SET prompt_de = 'Waren Sie im Ausland berufstätig? Bitte nennen Sie Zeitraum und Arbeitgeber.' WHERE id = '61000000-0000-0000-0000-000000000087';  -- abroad_employment_details
UPDATE public.question SET prompt_de = 'Wie lautet der Vorname des Kontoinhabers für mögliche Zahlungen?' WHERE id = '61000000-0000-0000-0000-000000000088';  -- payment_account_holder_first_name
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Max') WHERE id = '61000000-0000-0000-0000-000000000088';  -- payment_account_holder_first_name placeholder
UPDATE public.question SET prompt_de = 'Wie lautet der Nachname des Kontoinhabers für mögliche Zahlungen?' WHERE id = '61000000-0000-0000-0000-000000000089';  -- payment_account_holder_last_name
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Mustermann') WHERE id = '61000000-0000-0000-0000-000000000089';  -- payment_account_holder_last_name placeholder
UPDATE public.question SET prompt_de = 'Wie lautet die IBAN für mögliche Zahlungen?' WHERE id = '61000000-0000-0000-0000-00000000008a';  -- bank_giro_iban
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'DE89 3704 0044 0532 0130 00') WHERE id = '61000000-0000-0000-0000-00000000008a';  -- bank_giro_iban placeholder
UPDATE public.question SET prompt_de = 'Wie heißen die Bank und der Ort der Bank?' WHERE id = '61000000-0000-0000-0000-00000000008c';  -- bank_giro_name
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Sparkasse Berlin') WHERE id = '61000000-0000-0000-0000-00000000008c';  -- bank_giro_name placeholder
UPDATE public.question SET prompt_de = 'Ist das Konto ein Pfändungsschutzkonto (P-Konto)?' WHERE id = '61000000-0000-0000-0000-00000000008d';  -- p_account_yes_no
UPDATE public.question SET prompt_de = 'Warum stellen Sie den Antrag oder was möchten Sie uns noch mitteilen?' WHERE id = '61000000-0000-0000-0000-00000000008e';  -- application_reason_notes
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Pflegeheimkosten können nicht vollständig bezahlt werden') WHERE id = '61000000-0000-0000-0000-00000000008e';  -- application_reason_notes placeholder
UPDATE public.question SET prompt_de = 'Wie lautet der Nachname Ihres Ehepartners oder Partners?' WHERE id = '61000000-0000-0000-0000-00000000008f';  -- spouse_last_name
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Mustermann') WHERE id = '61000000-0000-0000-0000-00000000008f';  -- spouse_last_name placeholder
UPDATE public.question SET prompt_de = 'Wie lautet der Vorname Ihres Ehepartners oder Partners?' WHERE id = '61000000-0000-0000-0000-000000000090';  -- spouse_first_name
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Max') WHERE id = '61000000-0000-0000-0000-000000000090';  -- spouse_first_name placeholder
UPDATE public.question SET prompt_de = 'Wie lautet der Geburtsname Ihres Partners?' WHERE id = '61000000-0000-0000-0000-000000000091';  -- spouse_birth_name
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Müller') WHERE id = '61000000-0000-0000-0000-000000000091';  -- spouse_birth_name placeholder
UPDATE public.question SET prompt_de = 'Welches Geschlecht hat Ihr Partner?' WHERE id = '61000000-0000-0000-0000-000000000092';  -- spouse_gender
UPDATE public.question SET prompt_de = 'Wann wurde Ihr Partner geboren?' WHERE id = '61000000-0000-0000-0000-000000000093';  -- spouse_birthdate
UPDATE public.question SET prompt_de = 'In welchem Ort wurde Ihr Partner geboren?' WHERE id = '61000000-0000-0000-0000-000000000094';  -- spouse_city_of_birth
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Essen') WHERE id = '61000000-0000-0000-0000-000000000094';  -- spouse_city_of_birth placeholder
UPDATE public.question SET prompt_de = 'Wie lautet die Steuer-ID Ihres Partners?' WHERE id = '61000000-0000-0000-0000-000000000095';  -- spouse_tax_id
UPDATE public.question SET prompt_de = 'Wie lautet die Rentenversicherungsnummer Ihres Partners?' WHERE id = '61000000-0000-0000-0000-000000000096';  -- spouse_pension_insurance_number
UPDATE public.question SET prompt_de = 'Welche Staatsangehörigkeit hat Ihr Partner?' WHERE id = '61000000-0000-0000-0000-000000000097';  -- spouse_citizenship
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'deutsch') WHERE id = '61000000-0000-0000-0000-000000000097';  -- spouse_citizenship placeholder
UPDATE public.question SET prompt_de = 'Welchen Aufenthaltsstatus hat Ihr Partner?' WHERE id = '61000000-0000-0000-0000-000000000098';  -- spouse_residence_status
UPDATE public.question SET prompt_de = 'Wann ist Ihr Partner nach Deutschland eingereist?' WHERE id = '61000000-0000-0000-0000-000000000099';  -- spouse_entry_to_germany_date
UPDATE public.question SET prompt_de = 'Welchen sonstigen Aufenthaltsstatus hat Ihr Partner?' WHERE id = '61000000-0000-0000-0000-00000000009a';  -- spouse_residence_status_other
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Niederlassungserlaubnis') WHERE id = '61000000-0000-0000-0000-00000000009a';  -- spouse_residence_status_other placeholder
UPDATE public.question SET prompt_de = 'Hat Ihr Partner eine gesetzliche Betreuung oder eine bevollmächtigte Person?' WHERE id = '61000000-0000-0000-0000-00000000009b';  -- spouse_legal_guardian_yes_no
UPDATE public.question SET prompt_de = 'Wie heißt die Betreuung oder bevollmächtigte Person Ihres Partners, und wie ist die Adresse?' WHERE id = '61000000-0000-0000-0000-00000000009c';  -- spouse_legal_guardian_name_address
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Max Mustermann, Musterstraße 12') WHERE id = '61000000-0000-0000-0000-00000000009c';  -- spouse_legal_guardian_name_address placeholder
UPDATE public.question SET prompt_de = 'Hat Ihr Partner einen Schwerbehindertenausweis oder Feststellungsbescheid?' WHERE id = '61000000-0000-0000-0000-00000000009d';  -- spouse_disability_card
UPDATE public.question SET prompt_de = 'Bis wann ist der Schwerbehindertenausweis oder Feststellungsbescheid Ihres Partners gültig?' WHERE id = '61000000-0000-0000-0000-00000000009e';  -- spouse_disability_card_expiry
UPDATE public.question SET prompt_de = 'Wann wurde der Schwerbehindertenausweis oder Feststellungsbescheid für Ihren Partner beantragt?' WHERE id = '61000000-0000-0000-0000-00000000009f';  -- spouse_disability_card_application_date
UPDATE public.question SET prompt_de = 'Welche Merkzeichen stehen im Schwerbehindertenausweis Ihres Partners?' WHERE id = '61000000-0000-0000-0000-0000000000a0';  -- spouse_disability_card_markers
UPDATE public.question SET prompt_de = 'Bei welcher Krankenkasse ist Ihr Partner versichert?' WHERE id = '61000000-0000-0000-0000-0000000000a1';  -- spouse_health_insurance
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'AOK Rheinland/Hamburg') WHERE id = '61000000-0000-0000-0000-0000000000a1';  -- spouse_health_insurance placeholder
UPDATE public.question SET prompt_de = 'Wie ist Ihr Partner kranken- und pflegeversichert?' WHERE id = '61000000-0000-0000-0000-0000000000a3';  -- spouse_health_insurance_type
UPDATE public.question SET prompt_de = 'Wie lautet die Krankenversicherungsnummer Ihres Partners?' WHERE id = '61000000-0000-0000-0000-0000000000a4';  -- spouse_health_insurance_member_id
UPDATE public.question SET prompt_de = 'Wie hoch ist der monatliche Beitrag Ihres Partners zur Krankenversicherung?' WHERE id = '61000000-0000-0000-0000-0000000000a5';  -- spouse_health_insurance_amount
UPDATE public.question SET prompt_de = 'Wie hoch ist der monatliche Beitrag Ihres Partners zur Pflegeversicherung?' WHERE id = '61000000-0000-0000-0000-0000000000a6';  -- spouse_care_insurance_amount
UPDATE public.question SET prompt_de = 'Hat Ihr Partner eine ausländische Krankenversicherung?' WHERE id = '61000000-0000-0000-0000-0000000000a7';  -- spouse_foreign_health_insurance_yes_no
UPDATE public.question SET prompt_de = 'Wie heißen die ausländische Krankenversicherung Ihres Partners und ihre Adresse?' WHERE id = '61000000-0000-0000-0000-0000000000a8';  -- spouse_foreign_health_insurance_name_address
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Mutuelle Santé, Rue de Paris 1') WHERE id = '61000000-0000-0000-0000-0000000000a8';  -- spouse_foreign_health_insurance_name_address placeholder
UPDATE public.question SET prompt_de = 'Bei welcher Krankenkasse war Ihr Partner zuletzt versichert?' WHERE id = '61000000-0000-0000-0000-0000000000a9';  -- spouse_last_health_insurance
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Techniker Krankenkasse') WHERE id = '61000000-0000-0000-0000-0000000000a9';  -- spouse_last_health_insurance placeholder
UPDATE public.question SET prompt_de = 'Ab wann war Ihr Partner dort versichert?' WHERE id = '61000000-0000-0000-0000-0000000000aa';  -- spouse_last_health_insurance_from
UPDATE public.question SET prompt_de = 'Bis wann war Ihr Partner dort versichert?' WHERE id = '61000000-0000-0000-0000-0000000000ab';  -- spouse_last_health_insurance_until
UPDATE public.question SET prompt_de = 'Welche Rente oder Pension bekommt Ihr Partner?' WHERE id = '61000000-0000-0000-0000-0000000000ac';  -- spouse_pension_type
UPDATE public.question SET prompt_de = 'Wie hoch ist der Bruttobetrag dieser Rente oder Pension pro Monat?' WHERE id = '61000000-0000-0000-0000-0000000000ad';  -- spouse_pension_amount_gross
UPDATE public.question SET prompt_de = 'Wie hoch ist der Nettobetrag dieser Rente oder Pension pro Monat?' WHERE id = '61000000-0000-0000-0000-0000000000ae';  -- spouse_pension_amount
UPDATE public.question SET prompt_de = 'Hat Ihr Partner eine Rente beantragt, über die noch nicht entschieden wurde?' WHERE id = '61000000-0000-0000-0000-0000000000af';  -- spouse_pension_application_yes_no
UPDATE public.question SET prompt_de = 'Wann wurde die Rente Ihres Partners beantragt?' WHERE id = '61000000-0000-0000-0000-0000000000b0';  -- spouse_pension_application_date
UPDATE public.question SET prompt_de = 'Bei welcher Stelle wurde die Rente Ihres Partners beantragt?' WHERE id = '61000000-0000-0000-0000-0000000000b1';  -- spouse_pension_application_issuer
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Deutsche Rentenversicherung') WHERE id = '61000000-0000-0000-0000-0000000000b1';  -- spouse_pension_application_issuer placeholder
UPDATE public.question SET prompt_de = 'Welche Versicherungsnummer gehört zum Rentenantrag Ihres Partners?' WHERE id = '61000000-0000-0000-0000-0000000000b2';  -- spouse_pension_application_insurance_number
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', '12 010180 M 123') WHERE id = '61000000-0000-0000-0000-0000000000b2';  -- spouse_pension_application_insurance_number placeholder
UPDATE public.question SET prompt_de = 'Welche Rente wurde für Ihren Partner beantragt?' WHERE id = '61000000-0000-0000-0000-0000000000b3';  -- spouse_pension_application_type
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Altersrente') WHERE id = '61000000-0000-0000-0000-0000000000b3';  -- spouse_pension_application_type placeholder
UPDATE public.question SET prompt_de = 'Hat Ihr Partner weiteres Einkommen?' WHERE id = '61000000-0000-0000-0000-0000000000b4';  -- spouse_other_income
UPDATE public.question SET prompt_de = 'Welche Art von weiterem Einkommen hat Ihr Partner?' WHERE id = '61000000-0000-0000-0000-0000000000b5';  -- spouse_other_income_type
UPDATE public.question SET prompt_de = 'Wie hoch ist dieses Einkommen pro Monat?' WHERE id = '61000000-0000-0000-0000-0000000000b6';  -- spouse_other_income_amount
UPDATE public.question SET prompt_de = 'Wie viel Bargeld hat Ihr Partner?' WHERE id = '61000000-0000-0000-0000-0000000000b8';  -- spouse_cash_savings_amount
UPDATE public.question SET prompt_de = 'Hat Ihr Partner Bankguthaben?' WHERE id = '61000000-0000-0000-0000-0000000000b9';  -- spouse_bank_giro_yes_no
UPDATE public.question SET prompt_de = 'Wie hoch ist das Bankguthaben Ihres Partners?' WHERE id = '61000000-0000-0000-0000-0000000000ba';  -- spouse_bank_giro_amount
UPDATE public.question SET prompt_de = 'Hat Ihr Partner Sparguthaben?' WHERE id = '61000000-0000-0000-0000-0000000000bb';  -- spouse_bank_savings_account_yes_no
UPDATE public.question SET prompt_de = 'Wie hoch ist das Sparguthaben Ihres Partners?' WHERE id = '61000000-0000-0000-0000-0000000000bc';  -- spouse_bank_savings_account_amount
UPDATE public.question SET prompt_de = 'Hat Ihr Partner sonstige Kontoguthaben, z. B. PayPal?' WHERE id = '61000000-0000-0000-0000-0000000000bd';  -- spouse_bank_additional_account_yes_no
UPDATE public.question SET prompt_de = 'Wie hoch sind die sonstigen Kontoguthaben Ihres Partners?' WHERE id = '61000000-0000-0000-0000-0000000000be';  -- spouse_bank_additional_account_amount
UPDATE public.question SET prompt_de = 'Hat Ihr Partner einen Bestattungsvorsorgevertrag?' WHERE id = '61000000-0000-0000-0000-0000000000bf';  -- spouse_funeral_insurance_yes_no
UPDATE public.question SET prompt_de = 'Wie hoch ist der Betrag des Bestattungsvorsorgevertrags Ihres Partners?' WHERE id = '61000000-0000-0000-0000-0000000000c0';  -- spouse_funeral_insurance_amount
UPDATE public.question SET prompt_de = 'Hat Ihr Partner eine Kapital- oder Risikolebensversicherung?' WHERE id = '61000000-0000-0000-0000-0000000000c2';  -- spouse_life_insurance
UPDATE public.question SET prompt_de = 'Wie hoch ist der Betrag der Lebensversicherung Ihres Partners?' WHERE id = '61000000-0000-0000-0000-0000000000c3';  -- spouse_life_insurance_total_amount
UPDATE public.question SET prompt_de = 'Wie hoch ist der aktuelle Rückkaufswert der Lebensversicherung Ihres Partners?' WHERE id = '61000000-0000-0000-0000-0000000000c4';  -- spouse_life_insurance_surrender_value
UPDATE public.question SET prompt_de = 'Hat Ihr Partner ein Kraftfahrzeug?' WHERE id = '61000000-0000-0000-0000-0000000000c5';  -- spouse_automobile_yes_no
UPDATE public.question SET prompt_de = 'Welches amtliche Kennzeichen hat das Kraftfahrzeug Ihres Partners?' WHERE id = '61000000-0000-0000-0000-0000000000c6';  -- spouse_automobile_numbers_plate
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'E-AB 1234') WHERE id = '61000000-0000-0000-0000-0000000000c6';  -- spouse_automobile_numbers_plate placeholder
UPDATE public.question SET prompt_de = 'Aus welchem Baujahr ist das Kraftfahrzeug Ihres Partners?' WHERE id = '61000000-0000-0000-0000-0000000000c7';  -- spouse_automobile_year
UPDATE public.question SET prompt_de = 'Welches Fahrzeugmodell ist es?' WHERE id = '61000000-0000-0000-0000-0000000000c8';  -- spouse_automobile_type
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Golf') WHERE id = '61000000-0000-0000-0000-0000000000c8';  -- spouse_automobile_type placeholder
UPDATE public.question SET prompt_de = 'Welches ist der Fahrzeugtyp?' WHERE id = '61000000-0000-0000-0000-0000000000c9';  -- spouse_automobile_vehicle_type
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'VW') WHERE id = '61000000-0000-0000-0000-0000000000c9';  -- spouse_automobile_vehicle_type placeholder
UPDATE public.question SET prompt_de = 'Wie hoch ist der Kilometerstand des Kraftfahrzeugs Ihres Partners?' WHERE id = '61000000-0000-0000-0000-0000000000ca';  -- spouse_automobile_mileage
UPDATE public.question SET prompt_de = 'Hat Ihr Partner Haus- oder Wohneigentum?' WHERE id = '61000000-0000-0000-0000-0000000000cb';  -- spouse_property_yes_no
UPDATE public.question SET prompt_de = 'Bitte geben Sie Adresse, Art und Nutzung des Haus- oder Wohneigentums Ihres Partners an.' WHERE id = '61000000-0000-0000-0000-0000000000cc';  -- spouse_property_notes
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Eigentumswohnung, Musterstraße 12, vermietet') WHERE id = '61000000-0000-0000-0000-0000000000cc';  -- spouse_property_notes placeholder
UPDATE public.question SET prompt_de = 'Hat Ihr Partner sonstigen Grundbesitz?' WHERE id = '61000000-0000-0000-0000-0000000000cd';  -- spouse_additional_property_yes_no
UPDATE public.question SET prompt_de = 'Bitte geben Sie Adresse, Art und Nutzung des sonstigen Grundbesitzes Ihres Partners an.' WHERE id = '61000000-0000-0000-0000-0000000000ce';  -- spouse_additional_property_notes
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Garage, Musterstraße 12, vermietet') WHERE id = '61000000-0000-0000-0000-0000000000ce';  -- spouse_additional_property_notes placeholder
UPDATE public.question SET prompt_de = 'Hat Ihr Partner in den letzten 10 Jahren Vermögen an andere Personen übertragen?' WHERE id = '61000000-0000-0000-0000-0000000000cf';  -- spouse_asset_transfer_yes_no
UPDATE public.question SET prompt_de = 'Wann wurde das Vermögen Ihres Partners übertragen?' WHERE id = '61000000-0000-0000-0000-0000000000d0';  -- spouse_asset_transfer_date
UPDATE public.question SET prompt_de = 'In welcher Höhe wurde Vermögen Ihres Partners übertragen?' WHERE id = '61000000-0000-0000-0000-0000000000d1';  -- spouse_asset_transfer_amount
UPDATE public.question SET prompt_de = 'Trifft eine dieser seltenen Situationen auf Ihren Partner zu?' WHERE id = '61000000-0000-0000-0000-0000000000f1';  -- spouse_applicant_bulk_topics
UPDATE public.question SET prompt_de = 'Wann hat jemand bei der Ausländerbehörde unterschrieben, finanziell für Ihren Partner einzustehen?' WHERE id = '61000000-0000-0000-0000-0000000000d3';  -- spouse_commitment_declaration_date
UPDATE public.question SET prompt_de = 'Von welcher Stelle hat Ihr Partner diese Leistungen bekommen?' WHERE id = '61000000-0000-0000-0000-0000000000d4';  -- spouse_prior_sgb_benefits_provider
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Jobcenter Essen') WHERE id = '61000000-0000-0000-0000-0000000000d4';  -- spouse_prior_sgb_benefits_provider placeholder
UPDATE public.question SET prompt_de = 'Seit wann hat Ihr Partner diese Leistungen bekommen?' WHERE id = '61000000-0000-0000-0000-0000000000d5';  -- spouse_prior_sgb_benefits_from
UPDATE public.question SET prompt_de = 'Bis wann hat Ihr Partner diese Leistungen bekommen?' WHERE id = '61000000-0000-0000-0000-0000000000d6';  -- spouse_prior_sgb_benefits_until
UPDATE public.question SET prompt_de = 'Wann wurde der Antrag Ihres Partners nach dem Opferentschädigungsgesetz gestellt?' WHERE id = '61000000-0000-0000-0000-0000000000d7';  -- spouse_oeg_application_date
UPDATE public.question SET prompt_de = 'Bei welcher Stelle wurde der Antrag Ihres Partners nach dem Opferentschädigungsgesetz gestellt?' WHERE id = '61000000-0000-0000-0000-0000000000d8';  -- spouse_oeg_application_issuer
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Versorgungsamt Essen') WHERE id = '61000000-0000-0000-0000-0000000000d8';  -- spouse_oeg_application_issuer placeholder
UPDATE public.question SET prompt_de = 'In welchem Land und in welchem Zeitraum wurden für Ihren Partner ausländische Rentenbeiträge gezahlt?' WHERE id = '61000000-0000-0000-0000-0000000000d9';  -- spouse_foreign_pension_contributions_details
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Türkei, 1975-1980') WHERE id = '61000000-0000-0000-0000-0000000000d9';  -- spouse_foreign_pension_contributions_details placeholder
UPDATE public.question SET prompt_de = 'Wann und wo hat Ihr Partner im Ausland gearbeitet, ohne Rentenbeiträge zu zahlen?' WHERE id = '61000000-0000-0000-0000-0000000000da';  -- spouse_foreign_work_without_pension_contributions_details
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Türkei, 1975-1980, Firma Yilmaz, ca. 800 EUR/Monat') WHERE id = '61000000-0000-0000-0000-0000000000da';  -- spouse_foreign_work_without_pension_contributions_details placeholder
UPDATE public.question SET prompt_de = 'Wie hoch sind die monatlichen Sozialversicherungsbeiträge Ihres Partners?' WHERE id = '61000000-0000-0000-0000-0000000000dc';  -- spouse_social_security_contributions_amount
UPDATE public.question SET prompt_de = 'Wie hoch sind die monatlichen Altersvorsorgebeiträge?' WHERE id = '61000000-0000-0000-0000-0000000000e0';  -- spouse_pension_contributions_amount
UPDATE public.question SET prompt_de = 'Welchen Wert haben die Wertpapiere oder Aktien Ihres Partners?' WHERE id = '61000000-0000-0000-0000-0000000000e2';  -- spouse_securities_amount
UPDATE public.question SET prompt_de = 'Welchen Wert haben Schmuck oder Edelmetalle Ihres Partners?' WHERE id = '61000000-0000-0000-0000-0000000000e3';  -- spouse_jewelry_metals_amount
UPDATE public.question SET prompt_de = 'Welchen Wert hat das sonstige Vermögen Ihres Partners?' WHERE id = '61000000-0000-0000-0000-0000000000e4';  -- spouse_additional_wealth_amount
UPDATE public.question SET prompt_de = 'Welche Art von sonstigem Vermögen hat Ihr Partner?' WHERE id = '61000000-0000-0000-0000-0000000000e5';  -- spouse_additional_wealth_type
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Schmuck') WHERE id = '61000000-0000-0000-0000-0000000000e5';  -- spouse_additional_wealth_type placeholder
UPDATE public.question SET prompt_de = 'Wie hoch ist der Betrag der staatlich geförderten privaten Altersvorsorge Ihres Partners?' WHERE id = '61000000-0000-0000-0000-0000000000e6';  -- spouse_state_subsidized_private_pension_amount
UPDATE public.question SET prompt_de = 'Wann ist dieser Betrag fällig?' WHERE id = '61000000-0000-0000-0000-0000000000e7';  -- spouse_state_subsidized_private_pension_due_date
UPDATE public.question SET prompt_de = 'Wie hoch ist der Betrag der sonstigen privaten Altersvorsorge Ihres Partners?' WHERE id = '61000000-0000-0000-0000-0000000000e8';  -- spouse_private_pension_amount
UPDATE public.question SET prompt_de = 'Wann ist dieser Betrag fällig?' WHERE id = '61000000-0000-0000-0000-0000000000e9';  -- spouse_private_pension_due_date
UPDATE public.question SET prompt_de = 'Um welche Forderung oder welchen Anspruch Ihres Partners handelt es sich?' WHERE id = '61000000-0000-0000-0000-0000000000ea';  -- spouse_claims_against_third_parties_type
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Darlehen an Privatperson') WHERE id = '61000000-0000-0000-0000-0000000000ea';  -- spouse_claims_against_third_parties_type placeholder
UPDATE public.question SET prompt_de = 'Wie hoch ist die Forderung oder der Anspruch Ihres Partners?' WHERE id = '61000000-0000-0000-0000-0000000000eb';  -- spouse_claims_against_third_parties_amount
UPDATE public.question SET prompt_de = 'Hat Ihr Partner durch einen Vertrag noch Rechte an einem Haus, einer Wohnung oder einem Grundstück?' WHERE id = '61000000-0000-0000-0000-0000000000ec';  -- spouse_transfer_contract_claims_notes
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Ich darf weiterhin in der Wohnung wohnen') WHERE id = '61000000-0000-0000-0000-0000000000ec';  -- spouse_transfer_contract_claims_notes placeholder
UPDATE public.question SET prompt_de = 'Erwartet Ihr Partner eine Erbschaft oder hat er noch Anspruch auf etwas aus einer Erbschaft?' WHERE id = '61000000-0000-0000-0000-0000000000ed';  -- spouse_inheritance_claims_notes
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Erbe nach verstorbener Mutter noch nicht ausgezahlt') WHERE id = '61000000-0000-0000-0000-0000000000ed';  -- spouse_inheritance_claims_notes placeholder
UPDATE public.question SET prompt_de = 'In welchem Zeitraum hat Ihr Partner im Ausland gelebt?' WHERE id = '61000000-0000-0000-0000-0000000000ee';  -- spouse_abroad_stay_period
UPDATE public.question SET prompt_de = 'An welchem Wohnort im Ausland hat Ihr Partner gelebt?' WHERE id = '61000000-0000-0000-0000-0000000000ef';  -- spouse_abroad_stay_place
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Istanbul') WHERE id = '61000000-0000-0000-0000-0000000000ef';  -- spouse_abroad_stay_place placeholder
UPDATE public.question SET prompt_de = 'War Ihr Partner im Ausland berufstätig? Bitte nennen Sie Zeitraum und Arbeitgeber.' WHERE id = '61000000-0000-0000-0000-0000000000f0';  -- spouse_abroad_employment_details

-- ── Umlaut sweep (D2): labels/prompts only; option VALUES untouched ─────────
UPDATE public.question SET prompt_de = 'Gibt es eine oder mehrere dieser besonderen Vermögensarten?' WHERE id = '61000000-0000-0000-0000-0000000000f4';  -- sweep spouse_wealth_bulk_topics
UPDATE public.question_option SET label_de = 'EU-Ausländer/in' WHERE id = '71000000-0000-0000-000e-000000000001';  -- sweep option
UPDATE public.question_option SET label_de = 'Kriegs- oder Bürgerkriegsflüchtling' WHERE id = '71000000-0000-0000-000e-000000000002';  -- sweep option
UPDATE public.question_option SET label_de = 'Es besteht eine Verpflichtungserklärung nach § 68 Aufenthaltsgesetz' WHERE id = '71000000-0000-0000-0017-000000000000';  -- sweep option
UPDATE public.question_option SET label_de = 'Es ist eine medizinisch notwendige kostenaufwändige Ernährung erforderlich' WHERE id = '71000000-0000-0000-0017-000000000002';  -- sweep option
UPDATE public.question_option SET label_de = 'ausländische Rente/Pension' WHERE id = '71000000-0000-0000-0045-00000000000a';  -- sweep option
UPDATE public.question_option SET label_de = 'Es wurde ein Antrag nach dem Opferentschädigungsgesetz gestellt' WHERE id = '71000000-0000-0000-0050-000000000000';  -- sweep option
UPDATE public.question_option SET label_de = 'Es wurden freiwillige Beiträge in Rentenversicherung oder betriebliche Altersvorsorge eingezahlt' WHERE id = '71000000-0000-0000-0050-000000000001';  -- sweep option
UPDATE public.question_option SET label_de = 'Es wurde im Ausland gearbeitet, ohne dort Rentenbeiträge zu zahlen' WHERE id = '71000000-0000-0000-0050-000000000003';  -- sweep option
UPDATE public.question_option SET label_de = 'Es wurden 33 oder mehr Jahre Grundrentenzeiten erfüllt' WHERE id = '71000000-0000-0000-0050-000000000005';  -- sweep option
UPDATE public.question_option SET label_de = 'Es werden Sozialversicherungsbeiträge gezahlt' WHERE id = '71000000-0000-0000-0055-000000000001';  -- sweep option
UPDATE public.question_option SET label_de = 'Es werden Altersvorsorgebeiträge gezahlt' WHERE id = '71000000-0000-0000-0055-000000000005';  -- sweep option
UPDATE public.question_option SET label_de = 'Es werden Beiträge zu einer Sterbegeldversicherung gezahlt' WHERE id = '71000000-0000-0000-0055-000000000006';  -- sweep option
UPDATE public.question_option SET label_de = 'Ja - siehe beigefügte Urkunde' WHERE id = '71000000-0000-0000-0075-000000000002';  -- sweep option
UPDATE public.question_option SET label_de = 'Es gibt sonstiges Vermögen im In- oder Ausland' WHERE id = '71000000-0000-0000-0078-000000000002';  -- sweep option
UPDATE public.question_option SET label_de = 'Es gibt eine staatlich geförderte private Altersvorsorge' WHERE id = '71000000-0000-0000-0078-000000000003';  -- sweep option
UPDATE public.question_option SET label_de = 'Es gibt Forderungen oder Ansprüche gegen Dritte' WHERE id = '71000000-0000-0000-0078-000000000005';  -- sweep option
UPDATE public.question_option SET label_de = 'Es gibt Ansprüche aus Übertragsverträgen, Wohnrecht, Nießbrauch oder Altenteil' WHERE id = '71000000-0000-0000-0078-000000000006';  -- sweep option
UPDATE public.question_option SET label_de = 'Es gibt Ansprüche aus einer Erbschaft oder erwartete Erbschaft' WHERE id = '71000000-0000-0000-0078-000000000007';  -- sweep option
UPDATE public.question_option SET label_de = 'EU-Ausländer/in' WHERE id = '71000000-0000-0000-0098-000000000001';  -- sweep option
UPDATE public.question_option SET label_de = 'Kriegs- oder Bürgerkriegsflüchtling' WHERE id = '71000000-0000-0000-0098-000000000002';  -- sweep option
UPDATE public.question_option SET label_de = 'ausländische Rente/Pension' WHERE id = '71000000-0000-0000-00ac-00000000000a';  -- sweep option
UPDATE public.question_option SET label_de = 'Ja - siehe beigefügte Urkunde' WHERE id = '71000000-0000-0000-00cf-000000000002';  -- sweep option
UPDATE public.question_option SET label_de = 'Beim Partner besteht eine Verpflichtungserklärung nach § 68 Aufenthaltsgesetz' WHERE id = '71000000-0000-0000-00f1-000000000000';  -- sweep option
UPDATE public.question_option SET label_de = 'Der Partner hat früher bereits Leistungen nach SGB II oder SGB XI bezogen' WHERE id = '71000000-0000-0000-00f1-000000000001';  -- sweep option
UPDATE public.question_option SET label_de = 'Der Partner soll Verwaltungsakte oder Geldleistungen entgegennehmen dürfen' WHERE id = '71000000-0000-0000-00f1-000000000002';  -- sweep option
UPDATE public.question_option SET label_de = 'Der Partner hat einen Antrag nach dem Opferentschädigungsgesetz gestellt' WHERE id = '71000000-0000-0000-00f2-000000000000';  -- sweep option
UPDATE public.question_option SET label_de = 'Der Partner hat freiwillige Beiträge in Rentenversicherung oder betriebliche Altersvorsorge eingezahlt' WHERE id = '71000000-0000-0000-00f2-000000000001';  -- sweep option
UPDATE public.question_option SET label_de = 'Der Partner hat im Ausland gearbeitet, ohne dort Rentenbeiträge zu zahlen' WHERE id = '71000000-0000-0000-00f2-000000000003';  -- sweep option
UPDATE public.question_option SET label_de = 'Der Partner hat 33 oder mehr Jahre Grundrentenzeiten erfüllt' WHERE id = '71000000-0000-0000-00f2-000000000005';  -- sweep option
UPDATE public.question_option SET label_de = 'Der Partner zahlt Sozialversicherungsbeiträge' WHERE id = '71000000-0000-0000-00f3-000000000001';  -- sweep option
UPDATE public.question_option SET label_de = 'Der Partner zahlt Altersvorsorgebeiträge' WHERE id = '71000000-0000-0000-00f3-000000000005';  -- sweep option
UPDATE public.question_option SET label_de = 'Der Partner zahlt Beiträge zu einer Sterbegeldversicherung' WHERE id = '71000000-0000-0000-00f3-000000000006';  -- sweep option
UPDATE public.question_option SET label_de = 'Der Partner besitzt sonstiges Vermögen im In- oder Ausland' WHERE id = '71000000-0000-0000-00f4-000000000002';  -- sweep option
UPDATE public.question_option SET label_de = 'Der Partner hat eine staatlich geförderte private Altersvorsorge' WHERE id = '71000000-0000-0000-00f4-000000000003';  -- sweep option
UPDATE public.question_option SET label_de = 'Der Partner hat Forderungen oder Ansprüche gegen Dritte' WHERE id = '71000000-0000-0000-00f4-000000000005';  -- sweep option
UPDATE public.question_option SET label_de = 'Der Partner hat Ansprüche aus Übertragsverträgen, Wohnrecht, Nießbrauch oder Altenteil' WHERE id = '71000000-0000-0000-00f4-000000000006';  -- sweep option
UPDATE public.question_option SET label_de = 'Der Partner hat Ansprüche aus einer Erbschaft oder erwartet eine Erbschaft' WHERE id = '71000000-0000-0000-00f4-000000000007';  -- sweep option

COMMIT;
