-- Content pass 3 — Berlin copy updates (GENERATED by scripts/generate_cp3_copy.py from
-- docs/content/berlin_hzp_copy_changes.csv; do not hand-edit — re-run the generator).

BEGIN;

UPDATE public.question SET prompt_de = 'Haben Sie schon einmal Hilfe-zur-Pflege bekommen?' WHERE id = '60000000-0000-0000-0000-00000000000f';  -- prior_social_aid
UPDATE public.question SET prompt_de = 'Bis wann haben Sie Hilfe-zur-Pflege bekommen?' WHERE id = '60000000-0000-0000-0000-000000000010';  -- prior_social_aid_until
UPDATE public.question SET prompt_de = 'Welche Behörde hat die Hilfe-zur-Pflege bewilligt?' WHERE id = '60000000-0000-0000-0000-000000000011';  -- prior_social_aid_issuer
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Sozialamt Mitte') WHERE id = '60000000-0000-0000-0000-000000000011';  -- prior_social_aid_issuer placeholder
UPDATE public.question SET prompt_de = 'Welches Aktenzeichen steht auf dem Bescheid?' WHERE id = '60000000-0000-0000-0000-000000000012';  -- prior_social_aid_reference_id
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', '50-123456') WHERE id = '60000000-0000-0000-0000-000000000012';  -- prior_social_aid_reference_id placeholder
UPDATE public.question SET prompt_de = 'Haben Sie eine gesetzliche Betreuung oder eine bevollmächtigte Person?' WHERE id = '60000000-0000-0000-0000-000000000013';  -- power_of_attorney
UPDATE public.question SET prompt_de = 'Haben Sie einen Vertriebenen- oder Spätaussiedlerausweis?' WHERE id = '60000000-0000-0000-0000-000000000014';  -- special_origin_rights
UPDATE public.question SET prompt_de = 'Wann wurde der Ausweis ausgestellt?' WHERE id = '60000000-0000-0000-0000-000000000015';  -- special_origin_rights_issued
UPDATE public.question SET prompt_de = 'Welche Behörde hat den Ausweis ausgestellt?' WHERE id = '60000000-0000-0000-0000-000000000016';  -- special_origin_rights_issued_by
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Bundesverwaltungsamt') WHERE id = '60000000-0000-0000-0000-000000000016';  -- special_origin_rights_issued_by placeholder
UPDATE public.question SET prompt_de = 'Haben Sie einen Schwerbehindertenausweis?' WHERE id = '60000000-0000-0000-0000-000000000017';  -- disability_card
UPDATE public.question SET prompt_de = 'Haben Sie einen Schwerbehindertenausweis beantragt?' WHERE id = '60000000-0000-0000-0000-000000000018';  -- disablity_card_application
UPDATE public.question SET prompt_de = 'Bis wann ist Ihr Schwerbehindertenausweis gültig?' WHERE id = '60000000-0000-0000-0000-000000000019';  -- disability_card_expiry
UPDATE public.question SET prompt_de = 'Welche Merkzeichen stehen in Ihrem Schwerbehindertenausweis?' WHERE id = '60000000-0000-0000-0000-00000000001a';  -- disability_card_markers
UPDATE public.question SET prompt_de = 'Welchen Pflegegrad haben Sie?' WHERE id = '60000000-0000-0000-0000-00000000001d';  -- care_level
UPDATE public.question SET prompt_de = 'Wann sind Sie in das Pflegeheim eingezogen?' WHERE id = '60000000-0000-0000-0000-00000000001e';  -- in_facility_since
UPDATE public.question SET prompt_de = 'Wie lautete die Straße und Hausnummer Ihrer letzten Wohnung?' WHERE id = '60000000-0000-0000-0000-000000000023';  -- last_residence_street
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Musterstraße 12') WHERE id = '60000000-0000-0000-0000-000000000023';  -- last_residence_street placeholder
UPDATE public.question SET prompt_de = 'In welcher Stadt lag Ihre letzte Wohnung?' WHERE id = '60000000-0000-0000-0000-000000000024';  -- last_residence_city
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Berlin') WHERE id = '60000000-0000-0000-0000-000000000024';  -- last_residence_city placeholder
UPDATE public.question SET prompt_de = 'Wie haben Sie vor dem Einzug ins Pflegeheim gewohnt?' WHERE id = '60000000-0000-0000-0000-000000000028';  -- apartment_ownership
UPDATE public.question SET prompt_de = 'Wie heißen Ihr Vermieter und seine Adresse?' WHERE id = '60000000-0000-0000-0000-000000000029';  -- landlord_name_and_address
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Hausverwaltung Müller, Beispielweg 4') WHERE id = '60000000-0000-0000-0000-000000000029';  -- landlord_name_and_address placeholder
UPDATE public.question SET prompt_de = 'Wie hoch war Ihre monatliche Miete?' WHERE id = '60000000-0000-0000-0000-00000000002a';  -- rent_total
UPDATE public.question SET prompt_de = 'Wie hoch waren Ihre monatlichen Heizkosten?' WHERE id = '60000000-0000-0000-0000-00000000002b';  -- rent_heating
UPDATE public.question SET prompt_de = 'Wie hoch waren Ihre monatlichen Warmwasserkosten?' WHERE id = '60000000-0000-0000-0000-00000000002c';  -- rent_warm_water
UPDATE public.question SET prompt_de = 'Bis wann wurde die Miete schon bezahlt?' WHERE id = '60000000-0000-0000-0000-00000000002d';  -- rent_paid_until
UPDATE public.question SET prompt_de = 'Haben Sie Ihre letzte Wohnung bereits gekündigt?' WHERE id = '60000000-0000-0000-0000-00000000002f';  -- rent_contract_termination_yes_no
UPDATE public.question SET prompt_de = 'Zu welchem Datum wurde Ihre letzte Wohnung gekündigt?' WHERE id = '60000000-0000-0000-0000-000000000030';  -- rent_contract_terminated_by
UPDATE public.question SET prompt_de = 'Wie lautet der Vorname Ihres Kindes?' WHERE id = '60000000-0000-0000-0000-000000000031';  -- child_first_name
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Max') WHERE id = '60000000-0000-0000-0000-000000000031';  -- child_first_name placeholder
UPDATE public.question SET prompt_de = 'Wie lautet der Nachname Ihres Kindes?' WHERE id = '60000000-0000-0000-0000-000000000032';  -- child_last_name
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Mustermann') WHERE id = '60000000-0000-0000-0000-000000000032';  -- child_last_name placeholder
UPDATE public.question SET prompt_de = 'Wie lautet der Geburtsname Ihres Kindes?' WHERE id = '60000000-0000-0000-0000-000000000033';  -- child_birth_name
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Müller') WHERE id = '60000000-0000-0000-0000-000000000033';  -- child_birth_name placeholder
UPDATE public.question SET prompt_de = 'Wann wurde Ihr Kind geboren?' WHERE id = '60000000-0000-0000-0000-000000000034';  -- child_birth_date
UPDATE public.question SET prompt_de = 'Welchen Familienstand hat Ihr Kind?' WHERE id = '60000000-0000-0000-0000-000000000035';  -- child_marital_status
UPDATE public.question SET prompt_de = 'In welchem Verhältnis steht dieses Kind zu Ihnen?' WHERE id = '60000000-0000-0000-0000-000000000036';  -- child_family_tie
UPDATE public.question SET prompt_de = 'Welchen Beruf hat Ihr Kind?' WHERE id = '60000000-0000-0000-0000-000000000037';  -- child_profession
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Kauffrau') WHERE id = '60000000-0000-0000-0000-000000000037';  -- child_profession placeholder
UPDATE public.question SET prompt_de = 'Wie lautet die Wohnadresse Ihres Kindes?' WHERE id = '60000000-0000-0000-0000-000000000038';  -- child_address
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Musterstraße 12, 10115 Berlin') WHERE id = '60000000-0000-0000-0000-000000000038';  -- child_address placeholder
UPDATE public.question SET prompt_de = 'Welche Rente oder Pension bekommen Sie?' WHERE id = '60000000-0000-0000-0000-000000000039';  -- pension_type
UPDATE public.question SET prompt_de = 'Wie hoch ist diese Rente oder Pension pro Monat?' WHERE id = '60000000-0000-0000-0000-00000000003a';  -- pension_amount
UPDATE public.question SET prompt_de = 'Welche Abrechnungsnummer hat diese Rente oder Pension?' WHERE id = '60000000-0000-0000-0000-00000000003b';  -- pension_id
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'R123456789') WHERE id = '60000000-0000-0000-0000-00000000003b';  -- pension_id placeholder
UPDATE public.question SET prompt_de = 'Von wem bekommen Sie diese Rente oder Pension?' WHERE id = '60000000-0000-0000-0000-00000000003c';  -- pension_issuer
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Deutsche Rentenversicherung') WHERE id = '60000000-0000-0000-0000-00000000003c';  -- pension_issuer placeholder
UPDATE public.question SET prompt_de = 'Wie viel Wohngeld bekommen Sie pro Monat?' WHERE id = '60000000-0000-0000-0000-00000000003e';  -- wohngeld_amount
UPDATE public.question SET prompt_de = 'Welches Aktenzeichen steht auf Ihrem Wohngeldbescheid?' WHERE id = '60000000-0000-0000-0000-00000000003f';  -- wohngeld_id
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'WG-123456') WHERE id = '60000000-0000-0000-0000-00000000003f';  -- wohngeld_id placeholder
UPDATE public.question SET prompt_de = 'Haben Sie weiteres Einkommen?' WHERE id = '60000000-0000-0000-0000-000000000040';  -- other_income
UPDATE public.question SET prompt_de = 'Welche Art von weiterem Einkommen haben Sie?' WHERE id = '60000000-0000-0000-0000-000000000041';  -- other_income_type
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Mieteinnahmen') WHERE id = '60000000-0000-0000-0000-000000000041';  -- other_income_type placeholder
UPDATE public.question SET prompt_de = 'Wie hoch ist dieses weitere Einkommen pro Monat?' WHERE id = '60000000-0000-0000-0000-000000000042';  -- other_income_amount
UPDATE public.question SET prompt_de = 'Wie hoch ist Ihr monatlicher Beitrag zur Krankenversicherung?' WHERE id = '60000000-0000-0000-0000-000000000044';  -- health_insurance_amount
UPDATE public.question SET prompt_de = 'Wie hoch ist Ihr monatlicher Beitrag zur Pflegeversicherung?' WHERE id = '60000000-0000-0000-0000-000000000045';  -- care_insurance_amount
UPDATE public.question SET prompt_de = 'Bei welcher Versicherung haben Sie Ihre Haftpflichtversicherung?' WHERE id = '60000000-0000-0000-0000-000000000047';  -- general_liablity_insurance_provider
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'HUK-Coburg') WHERE id = '60000000-0000-0000-0000-000000000047';  -- general_liablity_insurance_provider placeholder
UPDATE public.question SET prompt_de = 'Wie hoch ist Ihr monatlicher Beitrag zur Haftpflichtversicherung?' WHERE id = '60000000-0000-0000-0000-000000000048';  -- general_liability_amount
UPDATE public.question SET prompt_de = 'Wie hoch ist Ihr monatlicher Beitrag für diese Versicherung?' WHERE id = '60000000-0000-0000-0000-00000000004a';  -- life_insurance_monthly_amount
UPDATE public.question SET prompt_de = 'Wie viel würde diese Versicherung auszahlen?' WHERE id = '60000000-0000-0000-0000-00000000004b';  -- life_insurance_total_amount
UPDATE public.question SET prompt_de = 'Bei welcher Versicherung haben Sie diese Versicherung?' WHERE id = '60000000-0000-0000-0000-00000000004c';  -- life_insurance_name
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Allianz') WHERE id = '60000000-0000-0000-0000-00000000004c';  -- life_insurance_name placeholder
UPDATE public.question SET prompt_de = 'Wie lautet die Versicherungsnummer?' WHERE id = '60000000-0000-0000-0000-00000000004d';  -- life_insurance_number
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'LV-123456') WHERE id = '60000000-0000-0000-0000-00000000004d';  -- life_insurance_number placeholder
UPDATE public.question SET prompt_de = 'Wie viel würde der Bestattungsvorsorgevertrag auszahlen?' WHERE id = '60000000-0000-0000-0000-00000000004f';  -- funeral_insurance_amount
UPDATE public.question SET prompt_de = 'Was trifft auf Ihren Bestattungsvorsorgevertrag zu?' WHERE id = '60000000-0000-0000-0000-000000000050';  -- funeral_insurance_detail
UPDATE public.question SET prompt_de = 'Wie lautet die Bankleitzahl Ihrer Bank?' WHERE id = '60000000-0000-0000-0000-000000000052';  -- bank_giro_blz
UPDATE public.question SET prompt_de = 'Wie lautet die IBAN Ihres Girokontos?' WHERE id = '60000000-0000-0000-0000-000000000053';  -- bank_giro_iban
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'DE89 3704 0044 0532 0130 00') WHERE id = '60000000-0000-0000-0000-000000000053';  -- bank_giro_iban placeholder
UPDATE public.question SET prompt_de = 'Haben Sie ein Sparkonto?' WHERE id = '60000000-0000-0000-0000-000000000055';  -- bank_savings_account_yes_no
UPDATE public.question SET prompt_de = 'Wie viel Geld ist auf Ihrem Sparkonto?' WHERE id = '60000000-0000-0000-0000-000000000056';  -- bank_savings_account_amount
UPDATE public.question SET prompt_de = 'Wie lautet die IBAN Ihres Sparkontos?' WHERE id = '60000000-0000-0000-0000-000000000057';  -- bank_savings_iban
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'DE89 3704 0044 0532 0130 00') WHERE id = '60000000-0000-0000-0000-000000000057';  -- bank_savings_iban placeholder
UPDATE public.question SET prompt_de = 'Haben Sie noch ein weiteres Konto?' WHERE id = '60000000-0000-0000-0000-000000000058';  -- bank_additional_account_yes_no
UPDATE public.question SET prompt_de = 'Bei welcher Bank ist dieses weitere Konto?' WHERE id = '60000000-0000-0000-0000-000000000059';  -- bank_additional_name
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Sparkasse Berlin') WHERE id = '60000000-0000-0000-0000-000000000059';  -- bank_additional_name placeholder
UPDATE public.question SET prompt_de = 'Wie lautet die IBAN dieses Kontos?' WHERE id = '60000000-0000-0000-0000-00000000005a';  -- bank_additional_iban
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'DE89 3704 0044 0532 0130 00') WHERE id = '60000000-0000-0000-0000-00000000005a';  -- bank_additional_iban placeholder
UPDATE public.question SET prompt_de = 'Wie viel Geld ist auf diesem Konto?' WHERE id = '60000000-0000-0000-0000-00000000005b';  -- bank_additional_amount
UPDATE public.question SET prompt_de = 'Wie viel Bargeld haben Sie?' WHERE id = '60000000-0000-0000-0000-00000000005c';  -- cash_savings
UPDATE public.question SET prompt_de = 'Haben Sie ein Auto?' WHERE id = '60000000-0000-0000-0000-00000000005d';  -- automobile_owner
UPDATE public.question SET prompt_de = 'Welches Kennzeichen hat Ihr Auto?' WHERE id = '60000000-0000-0000-0000-00000000005e';  -- automobile_numbers_plate
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'B-AB 1234') WHERE id = '60000000-0000-0000-0000-00000000005e';  -- automobile_numbers_plate placeholder
UPDATE public.question SET prompt_de = 'Welches Modell ist Ihr Auto?' WHERE id = '60000000-0000-0000-0000-00000000005f';  -- automobile_type
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'VW Golf') WHERE id = '60000000-0000-0000-0000-00000000005f';  -- automobile_type placeholder
UPDATE public.question SET prompt_de = 'Aus welchem Baujahr ist Ihr Auto?' WHERE id = '60000000-0000-0000-0000-000000000060';  -- automobile_year
UPDATE public.question SET prompt_de = 'Wer ist als Fahrzeughalter eingetragen?' WHERE id = '60000000-0000-0000-0000-000000000061';  -- automobile_holder
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Max Mustermann') WHERE id = '60000000-0000-0000-0000-000000000061';  -- automobile_holder placeholder
UPDATE public.question SET prompt_de = 'Haben Sie ein Haus, eine Wohnung oder ein Grundstück?' WHERE id = '60000000-0000-0000-0000-000000000062';  -- property_yes_no
UPDATE public.question SET prompt_de = 'Wie lautet die Adresse der Immobilie?' WHERE id = '60000000-0000-0000-0000-000000000063';  -- property_address
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Musterstraße 12, 10115 Berlin') WHERE id = '60000000-0000-0000-0000-000000000063';  -- property_address placeholder
UPDATE public.question SET prompt_de = 'Wie nutzen Sie die Immobilie?' WHERE id = '60000000-0000-0000-0000-000000000064';  -- property_usage
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'selbst genutzt') WHERE id = '60000000-0000-0000-0000-000000000064';  -- property_usage placeholder
UPDATE public.question SET prompt_de = 'Wie groß ist die Immobilie in Quadratmetern?' WHERE id = '60000000-0000-0000-0000-000000000065';  -- property_size
UPDATE public.question SET prompt_de = 'Haben Sie weitere Vermögenswerte?' WHERE id = '60000000-0000-0000-0000-000000000066';  -- additional_wealth_yes_no
UPDATE public.question SET prompt_de = 'Welche weiteren Vermögenswerte haben Sie?' WHERE id = '60000000-0000-0000-0000-000000000067';  -- additional_wealth_type
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Wertpapiere') WHERE id = '60000000-0000-0000-0000-000000000067';  -- additional_wealth_type placeholder
UPDATE public.question SET prompt_de = 'Wie viel ist dieser Vermögenswert ungefähr wert?' WHERE id = '60000000-0000-0000-0000-000000000068';  -- additional_wealth_amount
UPDATE public.question SET prompt_de = 'Brauchen Sie aus medizinischen Gründen eine besondere Ernährung, die mehr kostet?' WHERE id = '60000000-0000-0000-0000-000000000069';  -- costly_diet
UPDATE public.question SET prompt_de = 'Wie lautet der Nachname Ihres Ehepartners oder Partners?' WHERE id = '60000000-0000-0000-0000-00000000006a';  -- spouse_last_name
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Mustermann') WHERE id = '60000000-0000-0000-0000-00000000006a';  -- spouse_last_name placeholder
UPDATE public.question SET prompt_de = 'Wie lautet der Geburtsname Ihres Ehepartners oder Partners?' WHERE id = '60000000-0000-0000-0000-00000000006b';  -- spouse_birth_name
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Müller') WHERE id = '60000000-0000-0000-0000-00000000006b';  -- spouse_birth_name placeholder
UPDATE public.question SET prompt_de = 'Wie lautet der Vorname Ihres Partners?' WHERE id = '60000000-0000-0000-0000-00000000006c';  -- spouse_first_name
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Max') WHERE id = '60000000-0000-0000-0000-00000000006c';  -- spouse_first_name placeholder
UPDATE public.question SET prompt_de = 'Wann wurde Ihr Partner geboren?' WHERE id = '60000000-0000-0000-0000-00000000006d';  -- spouse_birthdate
UPDATE public.question SET prompt_de = 'In welcher Stadt wurde Ihr Partner geboren?' WHERE id = '60000000-0000-0000-0000-00000000006e';  -- spouse_city_of_birth
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Berlin') WHERE id = '60000000-0000-0000-0000-00000000006e';  -- spouse_city_of_birth placeholder
UPDATE public.question SET prompt_de = 'In welchem Kreis oder Bezirk wurde Ihr Partner geboren?' WHERE id = '60000000-0000-0000-0000-00000000006f';  -- spouse_district_of_birth
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Mitte') WHERE id = '60000000-0000-0000-0000-00000000006f';  -- spouse_district_of_birth placeholder
UPDATE public.question SET prompt_de = 'In welchem Land wurde Ihr Partner geboren?' WHERE id = '60000000-0000-0000-0000-000000000070';  -- spouse_country_of_birth
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Deutschland') WHERE id = '60000000-0000-0000-0000-000000000070';  -- spouse_country_of_birth placeholder
UPDATE public.question SET prompt_de = 'Welches Geschlecht hat Ihr Partner?' WHERE id = '60000000-0000-0000-0000-000000000071';  -- spouse_gender
UPDATE public.question SET prompt_de = 'Welche Staatsangehörigkeit hat Ihr Partner?' WHERE id = '60000000-0000-0000-0000-000000000072';  -- spouse_citizenship
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'deutsch') WHERE id = '60000000-0000-0000-0000-000000000072';  -- spouse_citizenship placeholder
UPDATE public.question SET prompt_de = 'Welche Behörde hat das Personaldokument Ihres Partners ausgestellt?' WHERE id = '60000000-0000-0000-0000-000000000073';  -- spouse_issuer_of_id
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Bezirksamt Mitte') WHERE id = '60000000-0000-0000-0000-000000000073';  -- spouse_issuer_of_id placeholder
UPDATE public.question SET prompt_de = 'Bis wann ist das Personaldokument Ihres Partners gültig?' WHERE id = '60000000-0000-0000-0000-000000000074';  -- spouse_id_expiry_date
UPDATE public.question SET prompt_de = 'Hat Ihr Partner schon einmal Hilfe-zur-Pflege bekommen?' WHERE id = '60000000-0000-0000-0000-000000000075';  -- spouse_prior_social_aid
UPDATE public.question SET prompt_de = 'Bis wann hat Ihr Partner Hilfe-zur-Pflege bekommen?' WHERE id = '60000000-0000-0000-0000-000000000076';  -- spouse_prior_social_aid_until
UPDATE public.question SET prompt_de = 'Welche Behörde hat die Hilfe-zur-Pflege bewilligt?' WHERE id = '60000000-0000-0000-0000-000000000077';  -- spouse_prior_social_aid_issuer
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Sozialamt Mitte') WHERE id = '60000000-0000-0000-0000-000000000077';  -- spouse_prior_social_aid_issuer placeholder
UPDATE public.question SET prompt_de = 'Welches Aktenzeichen steht auf dem Bescheid?' WHERE id = '60000000-0000-0000-0000-000000000078';  -- spouse_prior_social_aid_reference_id
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', '50-123456') WHERE id = '60000000-0000-0000-0000-000000000078';  -- spouse_prior_social_aid_reference_id placeholder
UPDATE public.question SET prompt_de = 'Hat Ihr Partner eine gesetzliche Betreuung oder eine bevollmächtigte Person?' WHERE id = '60000000-0000-0000-0000-000000000079';  -- spouse_power_of_attorney
UPDATE public.question SET prompt_de = 'Hat Ihr Partner einen Vertriebenen- oder Spätaussiedlerausweis?' WHERE id = '60000000-0000-0000-0000-00000000007a';  -- spouse_special_origin_rights
UPDATE public.question SET prompt_de = 'Wann wurde der Ausweis ausgestellt?' WHERE id = '60000000-0000-0000-0000-00000000007b';  -- spouse_special_origin_rights_issued
UPDATE public.question SET prompt_de = 'Welche Behörde hat den Ausweis ausgestellt?' WHERE id = '60000000-0000-0000-0000-00000000007c';  -- spouse_special_origin_rights_issued_by
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Bundesverwaltungsamt') WHERE id = '60000000-0000-0000-0000-00000000007c';  -- spouse_special_origin_rights_issued_by placeholder
UPDATE public.question SET prompt_de = 'Hat Ihr Partner einen Schwerbehindertenausweis?' WHERE id = '60000000-0000-0000-0000-00000000007d';  -- spouse_disability_card
UPDATE public.question SET prompt_de = 'Hat Ihr Partner einen Schwerbehindertenausweis beantragt?' WHERE id = '60000000-0000-0000-0000-00000000007e';  -- spouse_disability_card_application
UPDATE public.question SET prompt_de = 'Bis wann ist der Schwerbehindertenausweis Ihres Partners gültig?' WHERE id = '60000000-0000-0000-0000-00000000007f';  -- spouse_disability_card_expiry
UPDATE public.question SET prompt_de = 'Welche Merkzeichen stehen im Schwerbehindertenausweis Ihres Partners?' WHERE id = '60000000-0000-0000-0000-000000000080';  -- spouse_disability_card_markers
UPDATE public.question SET prompt_de = 'Bei welcher Krankenkasse ist Ihr Partner versichert?' WHERE id = '60000000-0000-0000-0000-000000000081';  -- spouse_health_insurance
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'AOK Nordost') WHERE id = '60000000-0000-0000-0000-000000000081';  -- spouse_health_insurance placeholder
UPDATE public.question SET prompt_de = 'Wie ist Ihr Partner krankenversichert?' WHERE id = '60000000-0000-0000-0000-000000000082';  -- spouse_health_insurance_type
UPDATE public.question SET prompt_de = 'Welchen Pflegegrad hat Ihr Partner?' WHERE id = '60000000-0000-0000-0000-000000000083';  -- spouse_care_level
UPDATE public.question SET prompt_de = 'Wohnt Ihr Partner in einem Pflegeheim?' WHERE id = '60000000-0000-0000-0000-000000000084';  -- spouse_in_facility_yes_no
UPDATE public.question SET prompt_de = 'Wann ist Ihr Partner in das Pflegeheim eingezogen?' WHERE id = '60000000-0000-0000-0000-000000000085';  -- spouse_in_facility_since
UPDATE public.question SET prompt_de = 'Hat Ihr Partner weitere Sozialleistungen beantragt?' WHERE id = '60000000-0000-0000-0000-000000000086';  -- spouse_prior_social_service_applications
UPDATE public.question SET prompt_de = 'Welche Rente oder Pension bekommt Ihr Partner?' WHERE id = '60000000-0000-0000-0000-000000000087';  -- spouse_pension_type
UPDATE public.question SET prompt_de = 'Wie hoch ist diese Rente oder Pension pro Monat?' WHERE id = '60000000-0000-0000-0000-000000000088';  -- spouse_pension_amount
UPDATE public.question SET prompt_de = 'Welche Abrechnungsnummer hat diese Rente oder Pension?' WHERE id = '60000000-0000-0000-0000-000000000089';  -- spouse_pension_id
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'R123456789') WHERE id = '60000000-0000-0000-0000-000000000089';  -- spouse_pension_id placeholder
UPDATE public.question SET prompt_de = 'Von wem bekommt Ihr Partner diese Rente oder Pension?' WHERE id = '60000000-0000-0000-0000-00000000008a';  -- spouse_pension_issuer
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Deutsche Rentenversicherung') WHERE id = '60000000-0000-0000-0000-00000000008a';  -- spouse_pension_issuer placeholder
UPDATE public.question SET prompt_de = 'Bekommt Ihr Partner Wohngeld?' WHERE id = '60000000-0000-0000-0000-00000000008b';  -- spouse_wohngeld_yes_no
UPDATE public.question SET prompt_de = 'Wie viel Wohngeld bekommt Ihr Partner pro Monat?' WHERE id = '60000000-0000-0000-0000-00000000008c';  -- spouse_wohngeld_amount
UPDATE public.question SET prompt_de = 'Welches Aktenzeichen steht auf dem Wohngeldbescheid?' WHERE id = '60000000-0000-0000-0000-00000000008d';  -- spouse_wohngeld_id
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'WG-123456') WHERE id = '60000000-0000-0000-0000-00000000008d';  -- spouse_wohngeld_id placeholder
UPDATE public.question SET prompt_de = 'Hat Ihr Partner weiteres Einkommen?' WHERE id = '60000000-0000-0000-0000-00000000008e';  -- spouse_other_income
UPDATE public.question SET prompt_de = 'Welche Art von weiterem Einkommen hat Ihr Partner?' WHERE id = '60000000-0000-0000-0000-00000000008f';  -- spouse_other_income_type
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Mieteinnahmen') WHERE id = '60000000-0000-0000-0000-00000000008f';  -- spouse_other_income_type placeholder
UPDATE public.question SET prompt_de = 'Wie hoch ist dieses weitere Einkommen pro Monat?' WHERE id = '60000000-0000-0000-0000-000000000090';  -- spouse_other_income_amount
UPDATE public.question SET prompt_de = 'Wie hoch ist der monatliche Beitrag zur Krankenversicherung Ihres Partners?' WHERE id = '60000000-0000-0000-0000-000000000091';  -- spouse_health_insurance_amount
UPDATE public.question SET prompt_de = 'Wie hoch ist der monatliche Beitrag zur Pflegeversicherung Ihres Partners?' WHERE id = '60000000-0000-0000-0000-000000000092';  -- spouse_care_insurance_amount
UPDATE public.question SET prompt_de = 'Hat Ihr Partner eine Haftpflichtversicherung?' WHERE id = '60000000-0000-0000-0000-000000000093';  -- spouse_general_liablity_insurance_yes_no
UPDATE public.question SET prompt_de = 'Bei welcher Versicherung hat Ihr Partner die Haftpflichtversicherung?' WHERE id = '60000000-0000-0000-0000-000000000094';  -- spouse_general_liablity_insurance_provider
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'HUK-Coburg') WHERE id = '60000000-0000-0000-0000-000000000094';  -- spouse_general_liablity_insurance_provider placeholder
UPDATE public.question SET prompt_de = 'Wie hoch ist der monatliche Beitrag zur Haftpflichtversicherung?' WHERE id = '60000000-0000-0000-0000-000000000095';  -- spouse_general_liability_amount
UPDATE public.question SET prompt_de = 'Hat Ihr Partner eine Lebens- oder Sterbeversicherung?' WHERE id = '60000000-0000-0000-0000-000000000096';  -- spouse_life_insurance
UPDATE public.question SET prompt_de = 'Wie hoch ist der monatliche Beitrag für diese Versicherung?' WHERE id = '60000000-0000-0000-0000-000000000097';  -- spouse_life_insurance_amount
UPDATE public.question SET prompt_de = 'Wie viel Geld ist auf dem Sparkonto Ihres Partners?' WHERE id = '60000000-0000-0000-0000-000000000098';  -- spouse_bank_savings_account_amount
UPDATE public.question SET prompt_de = 'Wie viel Geld ist auf dem Girokonto Ihres Partners?' WHERE id = '60000000-0000-0000-0000-000000000099';  -- spouse_bank_account_amount
UPDATE public.question SET prompt_de = 'Hat Ihr Partner ein Auto?' WHERE id = '60000000-0000-0000-0000-00000000009a';  -- spouse_automobile_owner
UPDATE public.question SET prompt_de = 'Welches Kennzeichen hat das Auto?' WHERE id = '60000000-0000-0000-0000-00000000009b';  -- spouse_automobile_numbers_plate
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'B-AB 1234') WHERE id = '60000000-0000-0000-0000-00000000009b';  -- spouse_automobile_numbers_plate placeholder
UPDATE public.question SET prompt_de = 'Welches Modell ist das Auto?' WHERE id = '60000000-0000-0000-0000-00000000009c';  -- spouse_automobile_type
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'VW Golf') WHERE id = '60000000-0000-0000-0000-00000000009c';  -- spouse_automobile_type placeholder
UPDATE public.question SET prompt_de = 'Aus welchem Baujahr ist das Auto?' WHERE id = '60000000-0000-0000-0000-00000000009d';  -- spouse_automobile_year
UPDATE public.question SET prompt_de = 'Wer ist als Fahrzeughalter eingetragen?' WHERE id = '60000000-0000-0000-0000-00000000009e';  -- spouse_automobile_holder
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Max Mustermann') WHERE id = '60000000-0000-0000-0000-00000000009e';  -- spouse_automobile_holder placeholder
UPDATE public.question SET prompt_de = 'Hat Ihr Partner ein Haus, eine Wohnung oder ein Grundstück?' WHERE id = '60000000-0000-0000-0000-00000000009f';  -- spouse_property_yes_no
UPDATE public.question SET prompt_de = 'Hat Ihr Partner weitere Vermögenswerte?' WHERE id = '60000000-0000-0000-0000-0000000000a0';  -- spouse_additional_wealth_yes_no
UPDATE public.question SET prompt_de = 'Welche weiteren Vermögenswerte hat Ihr Partner?' WHERE id = '60000000-0000-0000-0000-0000000000a1';  -- spouse_additional_wealth_type
UPDATE public.question SET validation = COALESCE(validation, '{}'::jsonb) || jsonb_build_object('placeholder_de', 'Wertpapiere') WHERE id = '60000000-0000-0000-0000-0000000000a1';  -- spouse_additional_wealth_type placeholder
UPDATE public.question SET prompt_de = 'Wie viel ist dieser Vermögenswert ungefähr wert?' WHERE id = '60000000-0000-0000-0000-0000000000a2';  -- spouse_additional_wealth_amount

COMMIT;
