/**
 * Essen document rules + evaluator extension (E1–E4) test matrix.
 *
 * The PANKOW REGRESSION is the gate: three representative answer sets
 * (F1 = pilot-shaped married case) evaluated against a committed snapshot of
 * the LIVE Pankow rules must produce byte-identical output to the goldens
 * captured with the pre-extension evaluator.
 *
 * Essen tests run against tests/fixtures/essen-rules.normalized.json — the
 * exact seed content the migration inserts (generated by
 * scripts/generate_essen_rules_seed.py from the canonical master).
 */

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'fs'
import { join } from 'path'
import {
  evaluateDocumentRules,
  type DocumentSlot,
  type OfficeDocumentRule,
  type EvalInput,
} from '@/lib/document-rules'
import { F1, F2, F3 } from '../fixtures/pankow-answer-fixtures.mjs'

const fixturesDir = join(__dirname, '..', 'fixtures')
const pankowSnap = JSON.parse(
  readFileSync(join(fixturesDir, 'pankow-rules.snapshot.json'), 'utf-8')
)
const pankowGolden = JSON.parse(
  readFileSync(join(fixturesDir, 'pankow-golden-slots.json'), 'utf-8')
)
const essen = JSON.parse(readFileSync(join(fixturesDir, 'essen-rules.normalized.json'), 'utf-8'))

const pankowCatalog = Object.fromEntries(
  (pankowSnap.catalog as { id: string }[]).map((c) => [c.id, c])
)
const essenRules = essen.rules as OfficeDocumentRule[]
const essenCatalog = essen.catalog as Record<string, { id: string; name_de: string }>

function evalEssen(input: Partial<EvalInput>) {
  return evaluateDocumentRules(essenRules, essenCatalog as never, {
    answers: {},
    groupInstances: {},
    groupAnswers: {},
    ...input,
  })
}
const ruleIds = (slots: DocumentSlot[]) => slots.map((s) => s.ruleId)
const ofRule = (slots: DocumentSlot[], id: string) => slots.filter((s) => s.ruleId === id)

const PARTNER_VALUES = ['verheiratet', 'Lebenspartnerschaft', 'eheähnliche Gemeinschaft']

// ── Gate: Pankow regression ───────────────────────────────────────────────────

describe('PANKOW REGRESSION GATE — output byte-identical to pre-extension goldens', () => {
  const fixtures = { F1, F2, F3 } as Record<string, EvalInput>
  for (const name of ['F1', 'F2', 'F3']) {
    it(`${name}${name === 'F1' ? ' (pilot-shaped married case)' : ''}`, () => {
      const now = evaluateDocumentRules(pankowSnap.rules, pankowCatalog as never, fixtures[name])
      expect(JSON.stringify(now)).toBe(JSON.stringify(pankowGolden[name]))
    })
  }
  it('no Pankow rule can reach the new code paths (operator/field census)', () => {
    const s = JSON.stringify(pankowSnap.rules)
    expect(s).not.toContain('"includes"')
    expect(s).not.toContain('match_values')
    expect(s).not.toContain('starts_with')
    expect(s).not.toContain('bank_giro_yes_no')
  })
})

// ── Phase C: PAN-011 deactivation (feedback pass 3, item 5) ───────────────────
// The DB flag is enforced at the QUERY layer (lib/dal.ts + case-export filter
// `active = true`), so the regression models exactly that: evaluate the live
// snapshot with inactive rules filtered out, and diff against the untouched
// goldens. The gate above still evaluates ALL snapshot rules, so it keeps
// proving the pre-existing behaviour byte-for-byte.

describe('PAN-011 deactivated — spouse Vollmacht slot gone, everything else identical', () => {
  const activeRules = (pankowSnap.rules as (OfficeDocumentRule & { active?: boolean })[]).filter(
    (r) => r.active !== false
  )

  it('the snapshot mirrors prod: exactly PAN-011 is inactive', () => {
    const inactive = (pankowSnap.rules as { id: string; active?: boolean }[])
      .filter((r) => r.active === false)
      .map((r) => r.id)
    expect(inactive).toEqual(['PAN-011'])
  })

  it('F1 (married): person_2 Vollmacht slot removed, remaining slots byte-identical', () => {
    const after = evaluateDocumentRules(activeRules, pankowCatalog as never, F1)
    const goldenWithout = (pankowGolden.F1 as DocumentSlot[]).filter((s) => s.ruleId !== 'PAN-011')

    // the slot that must disappear existed in the golden, and was the spouse Vollmacht
    const removed = (pankowGolden.F1 as DocumentSlot[]).filter((s) => s.ruleId === 'PAN-011')
    expect(removed).toHaveLength(1)
    expect(removed[0].subject).toBe('person_2')
    expect(removed[0].documentId).toBe('DOC-0006')

    expect(ofRule(after, 'PAN-011')).toHaveLength(0)
    expect(JSON.stringify(after)).toBe(JSON.stringify(goldenWithout))
    expect(after).toHaveLength((pankowGolden.F1 as DocumentSlot[]).length - 1)
  })

  it('the applicant Vollmacht (PAN-010, person_1) is untouched', () => {
    const after = evaluateDocumentRules(activeRules, pankowCatalog as never, F1)
    const pan010 = ofRule(after, 'PAN-010')
    expect(pan010).toHaveLength(1)
    expect(pan010[0].subject).toBe('person_1')
    expect(pan010[0].documentId).toBe('DOC-0006')
  })

  it('F2/F3 (single, separated): output identical — PAN-011 never fired for them', () => {
    for (const [name, fixture] of [
      ['F2', F2],
      ['F3', F3],
    ] as [string, EvalInput][]) {
      const after = evaluateDocumentRules(activeRules, pankowCatalog as never, fixture)
      expect(JSON.stringify(after), `${name} must be unchanged`).toBe(
        JSON.stringify(pankowGolden[name])
      )
    }
  })

  it('Essen married is unaffected: Vollmacht stays person_1-only (ESS-012)', () => {
    const slots = evalEssen({ answers: { marital_status: 'verheiratet' } })
    const vollmacht = slots.filter((s) => s.documentId === 'DOC-0006')
    expect(vollmacht).toHaveLength(1)
    expect(vollmacht[0].ruleId).toBe('ESS-012')
    expect(vollmacht[0].subject).toBe('person_1')
    // and Essen has no person_2 Vollmacht rule at all
    expect(essenRules.filter((r) => r.document_id === 'DOC-0006').map((r) => r.subject)).toEqual([
      'person_1',
    ])
  })
})

// ── Partner chain via the remapped per-domain spouse questions ────────────────

describe('partner chain — remapped spouse bulks (ESS-039)', () => {
  for (const marital of PARTNER_VALUES) {
    it(`fires under marital_status="${marital}"`, () => {
      const slots = evalEssen({
        answers: {
          marital_status: marital,
          spouse_expense_bulk_topics: ['Es besteht eine Haftpflichtversicherung'],
        },
      })
      expect(ofRule(slots, 'ESS-039')).toHaveLength(1)
    })
  }
  it('does not fire for ledig, and not without the bulk topic', () => {
    expect(
      ofRule(
        evalEssen({
          answers: {
            marital_status: 'ledig',
            spouse_expense_bulk_topics: ['Es besteht eine Haftpflichtversicherung'],
          },
        }),
        'ESS-039'
      )
    ).toHaveLength(0)
    expect(
      ofRule(evalEssen({ answers: { marital_status: 'verheiratet' } }), 'ESS-039')
    ).toHaveLength(0)
  })
})

// ── Pension slots per entry ───────────────────────────────────────────────────

describe('pension slots (ESS-003/004)', () => {
  it('one slot per pension entry; Keine Rente excluded', () => {
    const slots = evalEssen({
      groupInstances: { pension: ['p1', 'p2', 'p3'] },
      groupAnswers: {
        p1: { pension_type: 'Altersrente' },
        p2: { pension_type: 'Witwenrente' },
        p3: { pension_type: 'Keine Rente' },
      },
    })
    expect(ofRule(slots, 'ESS-003')).toHaveLength(2)
  })
  it('partner pensions only in the partner case', () => {
    const base = {
      groupInstances: { spouse_pension: ['sp1'] },
      groupAnswers: { sp1: { spouse_pension_type: 'Altersrente' } },
    }
    expect(
      ofRule(evalEssen({ ...base, answers: { marital_status: 'verheiratet' } }), 'ESS-004')
    ).toHaveLength(1)
    expect(
      ofRule(evalEssen({ ...base, answers: { marital_status: 'verwitwet' } }), 'ESS-004')
    ).toHaveLength(0)
  })
})

// ── Bank slots per account, gated (D2/E4) ─────────────────────────────────────

describe('bank slots (ESS-010/011) — per account, yes/no gated', () => {
  it('2 applicant accounts + 1 partner account → correct counts', () => {
    const slots = evalEssen({
      answers: {
        marital_status: 'verheiratet',
        bank_giro_yes_no: 'Ja',
        bank_savings_account_yes_no: 'Ja',
        spouse_bank_giro_yes_no: 'Ja',
        spouse_bank_savings_account_yes_no: 'Nein',
      },
    })
    expect(ofRule(slots, 'ESS-010')).toHaveLength(2) // giro + savings
    expect(ofRule(slots, 'ESS-011')).toHaveLength(1) // partner giro
  })
  it('E4 lifecycle: unanswered → giro present; Nein → absent; Ja → present', () => {
    expect(ofRule(evalEssen({}), 'ESS-010')).toHaveLength(1) // unanswered gate
    expect(ofRule(evalEssen({ answers: { bank_giro_yes_no: 'Nein' } }), 'ESS-010')).toHaveLength(0)
    expect(ofRule(evalEssen({ answers: { bank_giro_yes_no: 'Ja' } }), 'ESS-010')).toHaveLength(1)
  })
  it('account-less case → no bank slots', () => {
    const slots = evalEssen({
      answers: { bank_giro_yes_no: 'Nein', bank_savings_account_yes_no: 'Nein' },
    })
    expect(ofRule(slots, 'ESS-010')).toHaveLength(0)
  })
  it('additional-account instances add slots', () => {
    const slots = evalEssen({
      answers: { bank_giro_yes_no: 'Ja' },
      groupInstances: { bank_additional: ['b1'] },
      groupAnswers: { b1: { bank_additional_name: 'Sparkasse' } },
    })
    expect(ofRule(slots, 'ESS-010')).toHaveLength(2)
  })
  it('Berlin/Pankow giro emission unchanged (gate key not answerable there)', () => {
    // Same shape as the Pankow evaluator input: no bank_giro_yes_no key exists.
    const slots = evaluateDocumentRules(pankowSnap.rules, pankowCatalog as never, {
      answers: {},
      groupInstances: {},
      groupAnswers: {},
    })
    expect(slots.some((s) => s.ruleId === 'PAN-005' && s.instanceKey === 'giro')).toBe(true)
  })
})

// ── D1: per-matching-income-entry slots (E2) ──────────────────────────────────

describe('D1 filtered income slots (ESS-021)', () => {
  it('2 matching + 1 non-matching entries → 2 slots', () => {
    const slots = evalEssen({
      groupInstances: { other_income: ['i1', 'i2', 'i3'] },
      groupAnswers: {
        i1: { other_income_type: 'Mini-/Midijob' },
        i2: { other_income_type: 'Ausbildungsvergütung' },
        i3: { other_income_type: 'Unterhalt' },
      },
    })
    expect(ofRule(slots, 'ESS-021')).toHaveLength(2)
  })
  it('zero matching entries → zero slots (top-level binding, no flat fallback)', () => {
    const slots = evalEssen({
      groupInstances: { other_income: ['i1'] },
      groupAnswers: { i1: { other_income_type: 'Unterhalt' } },
    })
    expect(ofRule(slots, 'ESS-021')).toHaveLength(0)
  })
})

// ── E3: hybrid any (ESS-015) — chosen semantics ───────────────────────────────

describe('E3 hybrid any (ESS-015) — per-entry slots suppress the flat default', () => {
  const bulk = {
    applicant_bulk_topics: ['Es wurden frueher bereits Leistungen nach SGB II oder SGB XI bezogen'],
  }
  it('both true: matching entry + bulk topic → per-entry slot(s) only, no default', () => {
    const slots = ofRule(
      evalEssen({
        answers: { ...bulk },
        groupInstances: { other_income: ['i1'] },
        groupAnswers: { i1: { other_income_type: 'Bürgergeld/SGB II' } },
      }),
      'ESS-015'
    )
    expect(slots).toHaveLength(1)
    expect(slots[0].instanceKey).not.toBe('default')
  })
  it('flat-only: zero matching entries + bulk topic → exactly one default slot', () => {
    const slots = ofRule(evalEssen({ answers: { ...bulk } }), 'ESS-015')
    expect(slots).toHaveLength(1)
    expect(slots[0].instanceKey).toBe('default')
  })
  it('neither: no entry, no topic → no slot', () => {
    expect(ofRule(evalEssen({}), 'ESS-015')).toHaveLength(0)
  })
})

// ── ESS-047 remap: maintenance_claims_status ──────────────────────────────────

describe('ESS-047 — CP3 maintenance remap', () => {
  const NON_NEIN = [
    'Auf Unterhalt wurde verzichtet',
    'Unterhalt wird bereits bezahlt',
    'Unterhalt wurde noch nicht geltend gemacht',
    'Unterhalt ist bereits tituliert',
  ]
  for (const v of NON_NEIN) {
    it(`fires on "${v}"`, () => {
      expect(
        ofRule(evalEssen({ answers: { maintenance_claims_status: v } }), 'ESS-047')
      ).toHaveLength(1)
    })
  }
  it('does not fire on "Nein" or unanswered', () => {
    expect(
      ofRule(evalEssen({ answers: { maintenance_claims_status: 'Nein' } }), 'ESS-047')
    ).toHaveLength(0)
    expect(ofRule(evalEssen({}), 'ESS-047')).toHaveLength(0)
  })
})

// ── D3 rewrite (ESS-054) ──────────────────────────────────────────────────────

describe('ESS-054 — starts_with rewritten to any-of-equals', () => {
  for (const v of ['Ja - ohne besonderen Vertrag', 'Ja - siehe beigefuegte Urkunde']) {
    it(`fires on "${v}"`, () => {
      expect(ofRule(evalEssen({ answers: { asset_transfer_yes_no: v } }), 'ESS-054')).toHaveLength(
        1
      )
    })
  }
  it('does not fire on "Nein" or unanswered', () => {
    expect(
      ofRule(evalEssen({ answers: { asset_transfer_yes_no: 'Nein' } }), 'ESS-054')
    ).toHaveLength(0)
    expect(ofRule(evalEssen({}), 'ESS-054')).toHaveLength(0)
  })
})

// ── Minimal single applicant: exact mandatory slot set ────────────────────────

describe('minimal single applicant (one pension, one giro account)', () => {
  it('emits exactly ESS-001/003/005/006/007/008/010/012', () => {
    const slots = evalEssen({
      answers: {
        marital_status: 'ledig',
        bank_giro_yes_no: 'Ja',
        bank_savings_account_yes_no: 'Nein',
        pension_application_yes_no: 'Nein',
        disability_card: 'Nein',
        health_insurance_type: 'Pflichtversicherung',
        foreign_health_insurance_yes_no: 'Nein',
        former_rental_apartment_yes_no: 'Nein',
        funeral_insurance_yes_no: 'Nein',
        life_insurance: 'Nein',
        automobile_yes_no: 'Nein',
        property_yes_no: 'Nein',
        asset_transfer_yes_no: 'Nein',
        maintenance_claims_status: 'Nein',
      },
      groupInstances: { pension: ['p1'] },
      groupAnswers: { p1: { pension_type: 'Altersrente' } },
    })
    expect([...new Set(ruleIds(slots))].sort()).toEqual([
      'ESS-001',
      'ESS-003',
      'ESS-005',
      'ESS-006',
      'ESS-007',
      'ESS-008',
      'ESS-010',
      'ESS-012',
    ])
  })
})

// ── ESS-056: widowed → Sterbeurkunde Partner (Roman approved 2026-08-13, ─────
// round-2 item 4; the master's DOC-0016 Pankow-only tag is an approved
// override, see docs/document-rules/essen_document_rules.json)

describe('ESS-056 — Essen widowed applicants get the death-certificate slot', () => {
  it('widowed applicant gets exactly ONE Sterbeurkunde Partner slot (person_1)', () => {
    const slots = ofRule(evalEssen({ answers: { marital_status: 'verwitwet' } }), 'ESS-056')
    expect(slots).toHaveLength(1)
    expect(slots[0].subject).toBe('person_1')
    expect(slots[0].nameDe).toBe('Sterbeurkunde Partner')
    expect(slots[0].instanceKey).toBe('default')
  })

  it('does not fire for non-widowed or unanswered (fail-closed, PAN-025 semantics)', () => {
    for (const v of ['ledig', 'geschieden', 'getrennt lebend', ...PARTNER_VALUES]) {
      expect(ofRule(evalEssen({ answers: { marital_status: v } }), 'ESS-056')).toHaveLength(0)
    }
    expect(ofRule(evalEssen({}), 'ESS-056')).toHaveLength(0)
  })

  it('adding ESS-056 changes NOTHING else — outputs minus ESS-056 byte-identical to the pre-rule set', () => {
    const withoutRule = essenRules.filter((r) => r.id !== 'ESS-056')
    for (const answers of [
      {},
      { marital_status: 'verwitwet' },
      { marital_status: 'verheiratet' },
      { marital_status: 'ledig' },
    ]) {
      const before = evaluateDocumentRules(withoutRule, essenCatalog as never, {
        answers,
        groupInstances: {},
        groupAnswers: {},
      })
      const after = evalEssen({ answers }).filter((s) => s.ruleId !== 'ESS-056')
      expect(JSON.stringify(after)).toBe(JSON.stringify(before))
    }
  })
})
